# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: extend.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='extend.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n\x0c\x65xtend.proto\"/\n\x04\x62\x61se\x12\x11\n\ttimestamp\x18\x01 \x01(\x04\x12\r\n\x05owner\x18\x02 \x03(\t*\x05\x08\x64\x10\x91N:\x13\n\x04name\x12\x05.base\x18\x64 \x01(\t:\x12\n\x03res\x12\x05.base\x18\x65 \x03(\t'
)


NAME_FIELD_NUMBER = 100
name = _descriptor.FieldDescriptor(
  name='name', full_name='name', index=0,
  number=100, type=9, cpp_type=9, label=1,
  has_default_value=False, default_value=b"".decode('utf-8'),
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR)
RES_FIELD_NUMBER = 101
res = _descriptor.FieldDescriptor(
  name='res', full_name='res', index=1,
  number=101, type=9, cpp_type=9, label=3,
  has_default_value=False, default_value=[],
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR)


_BASE = _descriptor.Descriptor(
  name='base',
  full_name='base',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='base.timestamp', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='owner', full_name='base.owner', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=True,
  syntax='proto2',
  extension_ranges=[(100, 10001), ],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=63,
)

DESCRIPTOR.message_types_by_name['base'] = _BASE
DESCRIPTOR.extensions_by_name['name'] = name
DESCRIPTOR.extensions_by_name['res'] = res
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

base = _reflection.GeneratedProtocolMessageType('base', (_message.Message,), {
  'DESCRIPTOR' : _BASE,
  '__module__' : 'extend_pb2'
  # @@protoc_insertion_point(class_scope:base)
  })
_sym_db.RegisterMessage(base)

base.RegisterExtension(name)
base.RegisterExtension(res)

# @@protoc_insertion_point(module_scope)
