# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: main.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='main.proto',
  package='xuetu',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n\nmain.proto\x12\x05xuetu\"/\n\x04\x62\x61se\x12\x11\n\ttimestamp\x18\x01 \x01(\x04\x12\r\n\x05owner\x18\x02 \x03(\t*\x05\x08\x64\x10\x91N'
)




_BASE = _descriptor.Descriptor(
  name='base',
  full_name='xuetu.base',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='xuetu.base.timestamp', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='owner', full_name='xuetu.base.owner', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=True,
  syntax='proto2',
  extension_ranges=[(100, 10001), ],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=68,
)

DESCRIPTOR.message_types_by_name['base'] = _BASE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

base = _reflection.GeneratedProtocolMessageType('base', (_message.Message,), {
  'DESCRIPTOR' : _BASE,
  '__module__' : 'main_pb2'
  # @@protoc_insertion_point(class_scope:xuetu.base)
  })
_sym_db.RegisterMessage(base)


# @@protoc_insertion_point(module_scope)
