# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='msg.proto',
  package='ProtoCS',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n\tmsg.proto\x12\x07ProtoCS\"\x16\n\x07MsgHead\x12\x0b\n\x03\x63id\x18\x01 \x01(\x05\"9\n\x03Msg\x12\x1e\n\x04head\x18\x01 \x01(\x0b\x32\x10.ProtoCS.MsgHead\x12\x0b\n\x03ret\x18\x02 \x01(\x05*\x05\x08\x64\x10\x91N\"\x13\n\x06ModReq\x12\t\n\x01\x62\x18\x01 \x01(\x08*\x14\n\x05\x43mdID\x12\x0b\n\x07\x43ID_MOD\x10\x01:\x18\n\x02id\x12\x0c.ProtoCS.Msg\x18~ \x01(\x05:.\n\x07mod_req\x12\x0c.ProtoCS.Msg\x18\x7f \x01(\x0b\x32\x0f.ProtoCS.ModReq'
)

_CMDID = _descriptor.EnumDescriptor(
  name='CmdID',
  full_name='ProtoCS.CmdID',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CID_MOD', index=0, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=126,
  serialized_end=146,
)
_sym_db.RegisterEnumDescriptor(_CMDID)

CmdID = enum_type_wrapper.EnumTypeWrapper(_CMDID)
CID_MOD = 1

ID_FIELD_NUMBER = 126
id = _descriptor.FieldDescriptor(
  name='id', full_name='ProtoCS.id', index=0,
  number=126, type=5, cpp_type=1, label=1,
  has_default_value=False, default_value=0,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR)
MOD_REQ_FIELD_NUMBER = 127
mod_req = _descriptor.FieldDescriptor(
  name='mod_req', full_name='ProtoCS.mod_req', index=1,
  number=127, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR)


_MSGHEAD = _descriptor.Descriptor(
  name='MsgHead',
  full_name='ProtoCS.MsgHead',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cid', full_name='ProtoCS.MsgHead.cid', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=44,
)


_MSG = _descriptor.Descriptor(
  name='Msg',
  full_name='ProtoCS.Msg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='head', full_name='ProtoCS.Msg.head', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ret', full_name='ProtoCS.Msg.ret', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=True,
  syntax='proto2',
  extension_ranges=[(100, 10001), ],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=103,
)


_MODREQ = _descriptor.Descriptor(
  name='ModReq',
  full_name='ProtoCS.ModReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='b', full_name='ProtoCS.ModReq.b', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=105,
  serialized_end=124,
)

_MSG.fields_by_name['head'].message_type = _MSGHEAD
DESCRIPTOR.message_types_by_name['MsgHead'] = _MSGHEAD
DESCRIPTOR.message_types_by_name['Msg'] = _MSG
DESCRIPTOR.message_types_by_name['ModReq'] = _MODREQ
DESCRIPTOR.enum_types_by_name['CmdID'] = _CMDID
DESCRIPTOR.extensions_by_name['id'] = id
DESCRIPTOR.extensions_by_name['mod_req'] = mod_req
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MsgHead = _reflection.GeneratedProtocolMessageType('MsgHead', (_message.Message,), {
  'DESCRIPTOR' : _MSGHEAD,
  '__module__' : 'msg_pb2'
  # @@protoc_insertion_point(class_scope:ProtoCS.MsgHead)
  })
_sym_db.RegisterMessage(MsgHead)

Msg = _reflection.GeneratedProtocolMessageType('Msg', (_message.Message,), {
  'DESCRIPTOR' : _MSG,
  '__module__' : 'msg_pb2'
  # @@protoc_insertion_point(class_scope:ProtoCS.Msg)
  })
_sym_db.RegisterMessage(Msg)

ModReq = _reflection.GeneratedProtocolMessageType('ModReq', (_message.Message,), {
  'DESCRIPTOR' : _MODREQ,
  '__module__' : 'msg_pb2'
  # @@protoc_insertion_point(class_scope:ProtoCS.ModReq)
  })
_sym_db.RegisterMessage(ModReq)

Msg.RegisterExtension(id)
mod_req.message_type = _MODREQ
Msg.RegisterExtension(mod_req)

# @@protoc_insertion_point(module_scope)
