# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: person.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import main_pb2 as main__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='person.proto',
  package='xuetu',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n\x0cperson.proto\x12\x05xuetu\x1a\nmain.proto:\x19\n\x04name\x12\x0b.xuetu.base\x18\x64 \x01(\t:\x18\n\x03res\x12\x0b.xuetu.base\x18\x65 \x03(\t'
  ,
  dependencies=[main__pb2.DESCRIPTOR,])


NAME_FIELD_NUMBER = 100
name = _descriptor.FieldDescriptor(
  name='name', full_name='xuetu.name', index=0,
  number=100, type=9, cpp_type=9, label=1,
  has_default_value=False, default_value=b"".decode('utf-8'),
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR)
RES_FIELD_NUMBER = 101
res = _descriptor.FieldDescriptor(
  name='res', full_name='xuetu.res', index=1,
  number=101, type=9, cpp_type=9, label=3,
  has_default_value=False, default_value=[],
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR)

DESCRIPTOR.extensions_by_name['name'] = name
DESCRIPTOR.extensions_by_name['res'] = res
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

main__pb2.base.RegisterExtension(name)
main__pb2.base.RegisterExtension(res)

# @@protoc_insertion_point(module_scope)
