# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Account.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Account.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\rAccount.proto\"%\n\x13\x45mployeeNameRequest\x12\x0e\n\x06\x65mp_id\x18\x01 \x01(\t\"5\n\x0c\x45mployeeName\x12\x12\n\nfirst_name\x18\x01 \x01(\t\x12\x11\n\tlast_name\x18\x02 \x01(\t2H\n\x0e\x41\x63\x63ountService\x12\x36\n\x0fGetEmployeeName\x12\x14.EmployeeNameRequest\x1a\r.EmployeeNameb\x06proto3'
)




_EMPLOYEENAMEREQUEST = _descriptor.Descriptor(
  name='EmployeeNameRequest',
  full_name='EmployeeNameRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='emp_id', full_name='EmployeeNameRequest.emp_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=54,
)


_EMPLOYEENAME = _descriptor.Descriptor(
  name='EmployeeName',
  full_name='EmployeeName',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='first_name', full_name='EmployeeName.first_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='last_name', full_name='EmployeeName.last_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=109,
)

DESCRIPTOR.message_types_by_name['EmployeeNameRequest'] = _EMPLOYEENAMEREQUEST
DESCRIPTOR.message_types_by_name['EmployeeName'] = _EMPLOYEENAME
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EmployeeNameRequest = _reflection.GeneratedProtocolMessageType('EmployeeNameRequest', (_message.Message,), {
  'DESCRIPTOR' : _EMPLOYEENAMEREQUEST,
  '__module__' : 'Account_pb2'
  # @@protoc_insertion_point(class_scope:EmployeeNameRequest)
  })
_sym_db.RegisterMessage(EmployeeNameRequest)

EmployeeName = _reflection.GeneratedProtocolMessageType('EmployeeName', (_message.Message,), {
  'DESCRIPTOR' : _EMPLOYEENAME,
  '__module__' : 'Account_pb2'
  # @@protoc_insertion_point(class_scope:EmployeeName)
  })
_sym_db.RegisterMessage(EmployeeName)



_ACCOUNTSERVICE = _descriptor.ServiceDescriptor(
  name='AccountService',
  full_name='AccountService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=111,
  serialized_end=183,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetEmployeeName',
    full_name='AccountService.GetEmployeeName',
    index=0,
    containing_service=None,
    input_type=_EMPLOYEENAMEREQUEST,
    output_type=_EMPLOYEENAME,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ACCOUNTSERVICE)

DESCRIPTOR.services_by_name['AccountService'] = _ACCOUNTSERVICE

# @@protoc_insertion_point(module_scope)
