# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: anthor.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='anthor.proto',
  package='main',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0c\x61nthor.proto\x12\x04main\"=\n\x06\x41uthor\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04Name\x18\x02 \x01(\t\x12\x19\n\x05\x62ooks\x18\x03 \x03(\x0b\x32\n.main.Book\"D\n\x04\x42ook\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x1c\n\x04type\x18\x03 \x01(\x0e\x32\x0e.main.BookType\x12\x0c\n\x04name\x18\x05 \x01(\tJ\x04\x08\x02\x10\x03* \n\x08\x42ookType\x12\t\n\x05\x45\x42OOK\x10\x00\x12\t\n\x05PAPER\x10\x01\x62\x06proto3'
)

_BOOKTYPE = _descriptor.EnumDescriptor(
  name='BookType',
  full_name='main.BookType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='EBOOK', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PAPER', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=155,
  serialized_end=187,
)
_sym_db.RegisterEnumDescriptor(_BOOKTYPE)

BookType = enum_type_wrapper.EnumTypeWrapper(_BOOKTYPE)
EBOOK = 0
PAPER = 1



_AUTHOR = _descriptor.Descriptor(
  name='Author',
  full_name='main.Author',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='main.Author.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Name', full_name='main.Author.Name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='books', full_name='main.Author.books', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=83,
)


_BOOK = _descriptor.Descriptor(
  name='Book',
  full_name='main.Book',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='main.Book.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='main.Book.type', index=1,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='main.Book.name', index=2,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=85,
  serialized_end=153,
)

_AUTHOR.fields_by_name['books'].message_type = _BOOK
_BOOK.fields_by_name['type'].enum_type = _BOOKTYPE
DESCRIPTOR.message_types_by_name['Author'] = _AUTHOR
DESCRIPTOR.message_types_by_name['Book'] = _BOOK
DESCRIPTOR.enum_types_by_name['BookType'] = _BOOKTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Author = _reflection.GeneratedProtocolMessageType('Author', (_message.Message,), {
  'DESCRIPTOR' : _AUTHOR,
  '__module__' : 'anthor_pb2'
  # @@protoc_insertion_point(class_scope:main.Author)
  })
_sym_db.RegisterMessage(Author)

Book = _reflection.GeneratedProtocolMessageType('Book', (_message.Message,), {
  'DESCRIPTOR' : _BOOK,
  '__module__' : 'anthor_pb2'
  # @@protoc_insertion_point(class_scope:main.Book)
  })
_sym_db.RegisterMessage(Book)


# @@protoc_insertion_point(module_scope)
