# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: attendee.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='attendee.proto',
  package='voxxed.bristol',
  syntax='proto2',
  serialized_options=b'\n\027com.voxxed.bristol.pojoB\rAttendeeProto',
  serialized_pb=b'\n\x0e\x61ttendee.proto\x12\x0evoxxed.bristol\"\x9d\x01\n\x08\x41ttendee\x12\x12\n\nfirst_name\x18\x01 \x02(\t\x12\x11\n\tlast_name\x18\x02 \x02(\t\x12\x31\n\x07\x61\x64\x64ress\x18\x03 \x01(\x0b\x32 .voxxed.bristol.Attendee.Address\x1a\x37\n\x07\x41\x64\x64ress\x12\x0c\n\x04\x63ity\x18\x01 \x02(\t\x12\x0e\n\x06street\x18\x02 \x02(\t\x12\x0e\n\x06number\x18\x03 \x02(\x05\x42(\n\x17\x63om.voxxed.bristol.pojoB\rAttendeeProto'
)




_ATTENDEE_ADDRESS = _descriptor.Descriptor(
  name='Address',
  full_name='voxxed.bristol.Attendee.Address',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='city', full_name='voxxed.bristol.Attendee.Address.city', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='street', full_name='voxxed.bristol.Attendee.Address.street', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='number', full_name='voxxed.bristol.Attendee.Address.number', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=137,
  serialized_end=192,
)

_ATTENDEE = _descriptor.Descriptor(
  name='Attendee',
  full_name='voxxed.bristol.Attendee',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='first_name', full_name='voxxed.bristol.Attendee.first_name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='last_name', full_name='voxxed.bristol.Attendee.last_name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='address', full_name='voxxed.bristol.Attendee.address', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_ATTENDEE_ADDRESS, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=192,
)

_ATTENDEE_ADDRESS.containing_type = _ATTENDEE
_ATTENDEE.fields_by_name['address'].message_type = _ATTENDEE_ADDRESS
DESCRIPTOR.message_types_by_name['Attendee'] = _ATTENDEE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Attendee = _reflection.GeneratedProtocolMessageType('Attendee', (_message.Message,), {

  'Address' : _reflection.GeneratedProtocolMessageType('Address', (_message.Message,), {
    'DESCRIPTOR' : _ATTENDEE_ADDRESS,
    '__module__' : 'attendee_pb2'
    # @@protoc_insertion_point(class_scope:voxxed.bristol.Attendee.Address)
    })
  ,
  'DESCRIPTOR' : _ATTENDEE,
  '__module__' : 'attendee_pb2'
  # @@protoc_insertion_point(class_scope:voxxed.bristol.Attendee)
  })
_sym_db.RegisterMessage(Attendee)
_sym_db.RegisterMessage(Attendee.Address)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
