# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: awesome.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='awesome.proto',
  package='awesomepackage',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\rawesome.proto\x12\x0e\x61wesomepackage\"\'\n\x0e\x41wesomeMessage\x12\x15\n\rawesome_field\x18\x01 \x01(\tb\x06proto3'
)




_AWESOMEMESSAGE = _descriptor.Descriptor(
  name='AwesomeMessage',
  full_name='awesomepackage.AwesomeMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='awesome_field', full_name='awesomepackage.AwesomeMessage.awesome_field', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=72,
)

DESCRIPTOR.message_types_by_name['AwesomeMessage'] = _AWESOMEMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AwesomeMessage = _reflection.GeneratedProtocolMessageType('AwesomeMessage', (_message.Message,), {
  'DESCRIPTOR' : _AWESOMEMESSAGE,
  '__module__' : 'awesome_pb2'
  # @@protoc_insertion_point(class_scope:awesomepackage.AwesomeMessage)
  })
_sym_db.RegisterMessage(AwesomeMessage)


# @@protoc_insertion_point(module_scope)
