# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: book.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='book.proto',
  package='proto',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\nbook.proto\x12\x05proto\"\x19\n\tPublisher\x12\x0c\n\x04name\x18\x01 \x01(\t\"\xd3\x01\n\x04\x42ook\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\"\n\x06\x61uthor\x18\x02 \x01(\x0b\x32\x12.proto.Book.Author\x12\"\n\x04type\x18\x03 \x01(\x0e\x32\x14.proto.Book.BookType\x12#\n\tpublisher\x18\x04 \x01(\x0b\x32\x10.proto.Publisher\x1a\'\n\x06\x41uthor\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\"\'\n\x08\x42ookType\x12\x0b\n\x07SCIENCE\x10\x00\x12\x0e\n\nLITERATURE\x10\x01\x62\x06proto3'
)



_BOOK_BOOKTYPE = _descriptor.EnumDescriptor(
  name='BookType',
  full_name='proto.Book.BookType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SCIENCE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LITERATURE', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=221,
  serialized_end=260,
)
_sym_db.RegisterEnumDescriptor(_BOOK_BOOKTYPE)


_PUBLISHER = _descriptor.Descriptor(
  name='Publisher',
  full_name='proto.Publisher',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='proto.Publisher.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=46,
)


_BOOK_AUTHOR = _descriptor.Descriptor(
  name='Author',
  full_name='proto.Book.Author',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='proto.Book.Author.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='address', full_name='proto.Book.Author.address', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=180,
  serialized_end=219,
)

_BOOK = _descriptor.Descriptor(
  name='Book',
  full_name='proto.Book',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='proto.Book.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='author', full_name='proto.Book.author', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='proto.Book.type', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='publisher', full_name='proto.Book.publisher', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_BOOK_AUTHOR, ],
  enum_types=[
    _BOOK_BOOKTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=260,
)

_BOOK_AUTHOR.containing_type = _BOOK
_BOOK.fields_by_name['author'].message_type = _BOOK_AUTHOR
_BOOK.fields_by_name['type'].enum_type = _BOOK_BOOKTYPE
_BOOK.fields_by_name['publisher'].message_type = _PUBLISHER
_BOOK_BOOKTYPE.containing_type = _BOOK
DESCRIPTOR.message_types_by_name['Publisher'] = _PUBLISHER
DESCRIPTOR.message_types_by_name['Book'] = _BOOK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Publisher = _reflection.GeneratedProtocolMessageType('Publisher', (_message.Message,), {
  'DESCRIPTOR' : _PUBLISHER,
  '__module__' : 'book_pb2'
  # @@protoc_insertion_point(class_scope:proto.Publisher)
  })
_sym_db.RegisterMessage(Publisher)

Book = _reflection.GeneratedProtocolMessageType('Book', (_message.Message,), {

  'Author' : _reflection.GeneratedProtocolMessageType('Author', (_message.Message,), {
    'DESCRIPTOR' : _BOOK_AUTHOR,
    '__module__' : 'book_pb2'
    # @@protoc_insertion_point(class_scope:proto.Book.Author)
    })
  ,
  'DESCRIPTOR' : _BOOK,
  '__module__' : 'book_pb2'
  # @@protoc_insertion_point(class_scope:proto.Book)
  })
_sym_db.RegisterMessage(Book)
_sym_db.RegisterMessage(Book.Author)


# @@protoc_insertion_point(module_scope)
