# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calendar.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='calendar.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0e\x63\x61lendar.proto\"6\n\x05\x45vent\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x02 \x01(\t\x12\x11\n\trecurring\x18\x03 \x01(\x08\"\x1b\n\nEventAdded\x12\r\n\x05\x61\x64\x64\x65\x64\x18\x01 \x01(\x08\"&\n\nEventRange\x12\x0c\n\x04\x66rom\x18\x01 \x01(\t\x12\n\n\x02to\x18\x02 \x01(\t2T\n\x08\x43\x61lendar\x12!\n\x08\x41\x64\x64\x45vent\x12\x06.Event\x1a\x0b.EventAdded\"\x00\x12%\n\nShowEvents\x12\x0b.EventRange\x1a\x06.Event\"\x00\x30\x01\x62\x06proto3'
)




_EVENT = _descriptor.Descriptor(
  name='Event',
  full_name='Event',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='Event.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='date', full_name='Event.date', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='recurring', full_name='Event.recurring', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=72,
)


_EVENTADDED = _descriptor.Descriptor(
  name='EventAdded',
  full_name='EventAdded',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='added', full_name='EventAdded.added', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=101,
)


_EVENTRANGE = _descriptor.Descriptor(
  name='EventRange',
  full_name='EventRange',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='from', full_name='EventRange.from', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='to', full_name='EventRange.to', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=141,
)

DESCRIPTOR.message_types_by_name['Event'] = _EVENT
DESCRIPTOR.message_types_by_name['EventAdded'] = _EVENTADDED
DESCRIPTOR.message_types_by_name['EventRange'] = _EVENTRANGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Event = _reflection.GeneratedProtocolMessageType('Event', (_message.Message,), {
  'DESCRIPTOR' : _EVENT,
  '__module__' : 'calendar_pb2'
  # @@protoc_insertion_point(class_scope:Event)
  })
_sym_db.RegisterMessage(Event)

EventAdded = _reflection.GeneratedProtocolMessageType('EventAdded', (_message.Message,), {
  'DESCRIPTOR' : _EVENTADDED,
  '__module__' : 'calendar_pb2'
  # @@protoc_insertion_point(class_scope:EventAdded)
  })
_sym_db.RegisterMessage(EventAdded)

EventRange = _reflection.GeneratedProtocolMessageType('EventRange', (_message.Message,), {
  'DESCRIPTOR' : _EVENTRANGE,
  '__module__' : 'calendar_pb2'
  # @@protoc_insertion_point(class_scope:EventRange)
  })
_sym_db.RegisterMessage(EventRange)



_CALENDAR = _descriptor.ServiceDescriptor(
  name='Calendar',
  full_name='Calendar',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=143,
  serialized_end=227,
  methods=[
  _descriptor.MethodDescriptor(
    name='AddEvent',
    full_name='Calendar.AddEvent',
    index=0,
    containing_service=None,
    input_type=_EVENT,
    output_type=_EVENTADDED,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ShowEvents',
    full_name='Calendar.ShowEvents',
    index=1,
    containing_service=None,
    input_type=_EVENTRANGE,
    output_type=_EVENT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CALENDAR)

DESCRIPTOR.services_by_name['Calendar'] = _CALENDAR

# @@protoc_insertion_point(module_scope)
