# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cat.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cat.proto',
  package='demo',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\tcat.proto\x12\x04\x64\x65mo\"j\n\x03\x43\x61t\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03\x61ge\x18\x02 \x01(\x05\x12!\n\x07parents\x18\x04 \x03(\x0b\x32\x10.demo.Cat.Parent\x1a%\n\x06Parent\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\tb\x06proto3'
)




_CAT_PARENT = _descriptor.Descriptor(
  name='Parent',
  full_name='demo.Cat.Parent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='demo.Cat.Parent.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='email', full_name='demo.Cat.Parent.email', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=88,
  serialized_end=125,
)

_CAT = _descriptor.Descriptor(
  name='Cat',
  full_name='demo.Cat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='demo.Cat.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='age', full_name='demo.Cat.age', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='parents', full_name='demo.Cat.parents', index=2,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_CAT_PARENT, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=125,
)

_CAT_PARENT.containing_type = _CAT
_CAT.fields_by_name['parents'].message_type = _CAT_PARENT
DESCRIPTOR.message_types_by_name['Cat'] = _CAT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Cat = _reflection.GeneratedProtocolMessageType('Cat', (_message.Message,), {

  'Parent' : _reflection.GeneratedProtocolMessageType('Parent', (_message.Message,), {
    'DESCRIPTOR' : _CAT_PARENT,
    '__module__' : 'cat_pb2'
    # @@protoc_insertion_point(class_scope:demo.Cat.Parent)
    })
  ,
  'DESCRIPTOR' : _CAT,
  '__module__' : 'cat_pb2'
  # @@protoc_insertion_point(class_scope:demo.Cat)
  })
_sym_db.RegisterMessage(Cat)
_sym_db.RegisterMessage(Cat.Parent)


# @@protoc_insertion_point(module_scope)
