# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common2.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='common2.proto',
  package='go_proto',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n\rcommon2.proto\x12\x08go_proto\"B\n\nm_1101_toc\x12\x0b\n\x03\x63md\x18\x01 \x02(\r\x12\x12\n\nerror_code\x18\x02 \x02(\r\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t'
)




_M_1101_TOC = _descriptor.Descriptor(
  name='m_1101_toc',
  full_name='go_proto.m_1101_toc',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cmd', full_name='go_proto.m_1101_toc.cmd', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error_code', full_name='go_proto.m_1101_toc.error_code', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='description', full_name='go_proto.m_1101_toc.description', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=93,
)

DESCRIPTOR.message_types_by_name['m_1101_toc'] = _M_1101_TOC
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

m_1101_toc = _reflection.GeneratedProtocolMessageType('m_1101_toc', (_message.Message,), {
  'DESCRIPTOR' : _M_1101_TOC,
  '__module__' : 'common2_pb2'
  # @@protoc_insertion_point(class_scope:go_proto.m_1101_toc)
  })
_sym_db.RegisterMessage(m_1101_toc)


# @@protoc_insertion_point(module_scope)
