# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cover_helloworld.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cover_helloworld.proto',
  package='cover',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n\x16\x63over_helloworld.proto\x12\x05\x63over\"\\\n\nhelloworld\x1a\x1d\n\rhelloCoverReq\x12\x0c\n\x04name\x18\x01 \x02(\t\x1a/\n\rhelloCoverRsp\x12\x0f\n\x07retcode\x18\x01 \x02(\x05\x12\r\n\x05reply\x18\x02 \x01(\t'
)




_HELLOWORLD_HELLOCOVERREQ = _descriptor.Descriptor(
  name='helloCoverReq',
  full_name='cover.helloworld.helloCoverReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='cover.helloworld.helloCoverReq.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=76,
)

_HELLOWORLD_HELLOCOVERRSP = _descriptor.Descriptor(
  name='helloCoverRsp',
  full_name='cover.helloworld.helloCoverRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='retcode', full_name='cover.helloworld.helloCoverRsp.retcode', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reply', full_name='cover.helloworld.helloCoverRsp.reply', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=125,
)

_HELLOWORLD = _descriptor.Descriptor(
  name='helloworld',
  full_name='cover.helloworld',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[_HELLOWORLD_HELLOCOVERREQ, _HELLOWORLD_HELLOCOVERRSP, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=125,
)

_HELLOWORLD_HELLOCOVERREQ.containing_type = _HELLOWORLD
_HELLOWORLD_HELLOCOVERRSP.containing_type = _HELLOWORLD
DESCRIPTOR.message_types_by_name['helloworld'] = _HELLOWORLD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

helloworld = _reflection.GeneratedProtocolMessageType('helloworld', (_message.Message,), {

  'helloCoverReq' : _reflection.GeneratedProtocolMessageType('helloCoverReq', (_message.Message,), {
    'DESCRIPTOR' : _HELLOWORLD_HELLOCOVERREQ,
    '__module__' : 'cover_helloworld_pb2'
    # @@protoc_insertion_point(class_scope:cover.helloworld.helloCoverReq)
    })
  ,

  'helloCoverRsp' : _reflection.GeneratedProtocolMessageType('helloCoverRsp', (_message.Message,), {
    'DESCRIPTOR' : _HELLOWORLD_HELLOCOVERRSP,
    '__module__' : 'cover_helloworld_pb2'
    # @@protoc_insertion_point(class_scope:cover.helloworld.helloCoverRsp)
    })
  ,
  'DESCRIPTOR' : _HELLOWORLD,
  '__module__' : 'cover_helloworld_pb2'
  # @@protoc_insertion_point(class_scope:cover.helloworld)
  })
_sym_db.RegisterMessage(helloworld)
_sym_db.RegisterMessage(helloworld.helloCoverReq)
_sym_db.RegisterMessage(helloworld.helloCoverRsp)


# @@protoc_insertion_point(module_scope)
