# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='data.proto',
  package='main',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n\ndata.proto\x12\x04main\"\'\n\x04\x44\x65mo\x12\t\n\x01\x41\x18\x01 \x02(\r\x12\t\n\x01\x42\x18\x02 \x02(\r\x12\t\n\x01\x43\x18\x03 \x02(\r'
)




_DEMO = _descriptor.Descriptor(
  name='Demo',
  full_name='main.Demo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='A', full_name='main.Demo.A', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='B', full_name='main.Demo.B', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='C', full_name='main.Demo.C', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=59,
)

DESCRIPTOR.message_types_by_name['Demo'] = _DEMO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Demo = _reflection.GeneratedProtocolMessageType('Demo', (_message.Message,), {
  'DESCRIPTOR' : _DEMO,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:main.Demo)
  })
_sym_db.RegisterMessage(Demo)


# @@protoc_insertion_point(module_scope)
