# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: demo5.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='demo5.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0b\x64\x65mo5.proto\"%\n\x04\x44\x65mo\x12\r\n\x05query\x18\x01 \x01(\t\x12\x0e\n\x06number\x18\x02 \x01(\x05\x62\x06proto3'
)




_DEMO = _descriptor.Descriptor(
  name='Demo',
  full_name='Demo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='query', full_name='Demo.query', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='number', full_name='Demo.number', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=52,
)

DESCRIPTOR.message_types_by_name['Demo'] = _DEMO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Demo = _reflection.GeneratedProtocolMessageType('Demo', (_message.Message,), {
  'DESCRIPTOR' : _DEMO,
  '__module__' : 'demo5_pb2'
  # @@protoc_insertion_point(class_scope:Demo)
  })
_sym_db.RegisterMessage(Demo)


# @@protoc_insertion_point(module_scope)
