# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: demo7.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='demo7.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n\x0b\x64\x65mo7.proto\"\x0f\n\x01\x42\x12\n\n\x02\x62\x32\x18\x02 \x01(\t\"\x1e\n\x01\x41\x12\r\n\x01\x62\x18\x01 \x03(\x0b\x32\x02.B\x12\n\n\x02id\x18\x02 \x01(\t'
)




_B = _descriptor.Descriptor(
  name='B',
  full_name='B',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='b2', full_name='B.b2', index=0,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=30,
)


_A = _descriptor.Descriptor(
  name='A',
  full_name='A',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='b', full_name='A.b', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='A.id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=62,
)

_A.fields_by_name['b'].message_type = _B
DESCRIPTOR.message_types_by_name['B'] = _B
DESCRIPTOR.message_types_by_name['A'] = _A
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

B = _reflection.GeneratedProtocolMessageType('B', (_message.Message,), {
  'DESCRIPTOR' : _B,
  '__module__' : 'demo7_pb2'
  # @@protoc_insertion_point(class_scope:B)
  })
_sym_db.RegisterMessage(B)

A = _reflection.GeneratedProtocolMessageType('A', (_message.Message,), {
  'DESCRIPTOR' : _A,
  '__module__' : 'demo7_pb2'
  # @@protoc_insertion_point(class_scope:A)
  })
_sym_db.RegisterMessage(A)


# @@protoc_insertion_point(module_scope)
