# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: demo2.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='demo2.proto',
  package='model',
  syntax='proto3',
  serialized_options=b'\n+org.abondar.experimental.protobufdemo.modelB\006Person',
  serialized_pb=b'\n\x0b\x64\x65mo2.proto\x12\x05model\"\xfa\x01\n\tPersonMsg\x12\x11\n\tfirstName\x18\x01 \x01(\t\x12\x10\n\x08lastName\x18\x02 \x01(\t\x12\n\n\x02id\x18\x03 \x01(\x05\x12\r\n\x05\x65mail\x18\x04 \x01(\t\x12&\n\x03\x65mp\x18\x05 \x01(\x0e\x32\x19.model.PersonMsg.Employee\x12/\n\ndepartment\x18\x06 \x01(\x0b\x32\x1b.model.PersonMsg.Department\x1a$\n\nDepartment\x12\x16\n\x0e\x64\x65partmentName\x18\x01 \x01(\t\".\n\x08\x45mployee\x12\r\n\tDEVELOPER\x10\x00\x12\x06\n\x02QA\x10\x01\x12\x0b\n\x07MANAGER\x10\x02\x42\x35\n+org.abondar.experimental.protobufdemo.modelB\x06Personb\x06proto3'
)



_PERSONMSG_EMPLOYEE = _descriptor.EnumDescriptor(
  name='Employee',
  full_name='model.PersonMsg.Employee',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DEVELOPER', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='QA', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MANAGER', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=227,
  serialized_end=273,
)
_sym_db.RegisterEnumDescriptor(_PERSONMSG_EMPLOYEE)


_PERSONMSG_DEPARTMENT = _descriptor.Descriptor(
  name='Department',
  full_name='model.PersonMsg.Department',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='departmentName', full_name='model.PersonMsg.Department.departmentName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=189,
  serialized_end=225,
)

_PERSONMSG = _descriptor.Descriptor(
  name='PersonMsg',
  full_name='model.PersonMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='firstName', full_name='model.PersonMsg.firstName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lastName', full_name='model.PersonMsg.lastName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='model.PersonMsg.id', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='email', full_name='model.PersonMsg.email', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='emp', full_name='model.PersonMsg.emp', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='department', full_name='model.PersonMsg.department', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_PERSONMSG_DEPARTMENT, ],
  enum_types=[
    _PERSONMSG_EMPLOYEE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=273,
)

_PERSONMSG_DEPARTMENT.containing_type = _PERSONMSG
_PERSONMSG.fields_by_name['emp'].enum_type = _PERSONMSG_EMPLOYEE
_PERSONMSG.fields_by_name['department'].message_type = _PERSONMSG_DEPARTMENT
_PERSONMSG_EMPLOYEE.containing_type = _PERSONMSG
DESCRIPTOR.message_types_by_name['PersonMsg'] = _PERSONMSG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PersonMsg = _reflection.GeneratedProtocolMessageType('PersonMsg', (_message.Message,), {

  'Department' : _reflection.GeneratedProtocolMessageType('Department', (_message.Message,), {
    'DESCRIPTOR' : _PERSONMSG_DEPARTMENT,
    '__module__' : 'demo2_pb2'
    # @@protoc_insertion_point(class_scope:model.PersonMsg.Department)
    })
  ,
  'DESCRIPTOR' : _PERSONMSG,
  '__module__' : 'demo2_pb2'
  # @@protoc_insertion_point(class_scope:model.PersonMsg)
  })
_sym_db.RegisterMessage(PersonMsg)
_sym_db.RegisterMessage(PersonMsg.Department)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
