# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: demo3.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='demo3.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\n\021com.demo.protobufB\014DemoProtoBuf',
  serialized_pb=b'\n\x0b\x64\x65mo3.proto\"\xac\x01\n\x04\x44\x65mo\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\t\x12\r\n\x05likes\x18\x03 \x03(\t\x1a>\n\x0b\x44\x65moMessage\x12\x1a\n\x05\x63olor\x18\x01 \x01(\x0e\x32\x0b.Demo.Color\x12\x13\n\x0bmessageData\x18\x02 \x01(\x05\":\n\x05\x43olor\x12\x07\n\x03RED\x10\x00\x12\x08\n\x04\x42LUE\x10\x07\"\x04\x08\x03\x10\x03\"\x04\x08\x04\x10\x04\"\x04\x08\x05\x10\x05*\x05\x42LACK*\x05WHITEB!\n\x11\x63om.demo.protobufB\x0c\x44\x65moProtoBufb\x06proto3'
)



_DEMO_COLOR = _descriptor.EnumDescriptor(
  name='Color',
  full_name='Demo.Color',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='RED', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BLUE', index=1, number=7,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=130,
  serialized_end=188,
)
_sym_db.RegisterEnumDescriptor(_DEMO_COLOR)


_DEMO_DEMOMESSAGE = _descriptor.Descriptor(
  name='DemoMessage',
  full_name='Demo.DemoMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='color', full_name='Demo.DemoMessage.color', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='messageData', full_name='Demo.DemoMessage.messageData', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=128,
)

_DEMO = _descriptor.Descriptor(
  name='Demo',
  full_name='Demo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Demo.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='Demo.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='likes', full_name='Demo.likes', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_DEMO_DEMOMESSAGE, ],
  enum_types=[
    _DEMO_COLOR,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=188,
)

_DEMO_DEMOMESSAGE.fields_by_name['color'].enum_type = _DEMO_COLOR
_DEMO_DEMOMESSAGE.containing_type = _DEMO
_DEMO_COLOR.containing_type = _DEMO
DESCRIPTOR.message_types_by_name['Demo'] = _DEMO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Demo = _reflection.GeneratedProtocolMessageType('Demo', (_message.Message,), {

  'DemoMessage' : _reflection.GeneratedProtocolMessageType('DemoMessage', (_message.Message,), {
    'DESCRIPTOR' : _DEMO_DEMOMESSAGE,
    '__module__' : 'demo3_pb2'
    # @@protoc_insertion_point(class_scope:Demo.DemoMessage)
    })
  ,
  'DESCRIPTOR' : _DEMO,
  '__module__' : 'demo3_pb2'
  # @@protoc_insertion_point(class_scope:Demo)
  })
_sym_db.RegisterMessage(Demo)
_sym_db.RegisterMessage(Demo.DemoMessage)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
