# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dog.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='dog.proto',
  package='demo',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\tdog.proto\x12\x04\x64\x65mo\"p\n\x03\x44og\x12\r\n\x05\x62\x61rks\x18\x01 \x01(\x08\x12\x10\n\x08yearsold\x18\x02 \x01(\x05\x12!\n\x07parents\x18\x04 \x03(\x0b\x32\x10.demo.Dog.Parent\x1a%\n\x06Parent\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\tb\x06proto3'
)




_DOG_PARENT = _descriptor.Descriptor(
  name='Parent',
  full_name='demo.Dog.Parent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='demo.Dog.Parent.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='email', full_name='demo.Dog.Parent.email', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=94,
  serialized_end=131,
)

_DOG = _descriptor.Descriptor(
  name='Dog',
  full_name='demo.Dog',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='barks', full_name='demo.Dog.barks', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='yearsold', full_name='demo.Dog.yearsold', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='parents', full_name='demo.Dog.parents', index=2,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_DOG_PARENT, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=131,
)

_DOG_PARENT.containing_type = _DOG
_DOG.fields_by_name['parents'].message_type = _DOG_PARENT
DESCRIPTOR.message_types_by_name['Dog'] = _DOG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Dog = _reflection.GeneratedProtocolMessageType('Dog', (_message.Message,), {

  'Parent' : _reflection.GeneratedProtocolMessageType('Parent', (_message.Message,), {
    'DESCRIPTOR' : _DOG_PARENT,
    '__module__' : 'dog_pb2'
    # @@protoc_insertion_point(class_scope:demo.Dog.Parent)
    })
  ,
  'DESCRIPTOR' : _DOG,
  '__module__' : 'dog_pb2'
  # @@protoc_insertion_point(class_scope:demo.Dog)
  })
_sym_db.RegisterMessage(Dog)
_sym_db.RegisterMessage(Dog.Parent)


# @@protoc_insertion_point(module_scope)
