# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: employee.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='employee.proto',
  package='employee',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0e\x65mployee.proto\x12\x08\x65mployee\"\x1d\n\x0f\x45mployeeRequest\x12\n\n\x02id\x18\x01 \x01(\x05\">\n\x10\x45mployeeResponse\x12*\n\x07message\x18\x01 \x01(\x0b\x32\x19.employee.EmployeeDetails\"Q\n\x0f\x45mployeeDetails\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x11\n\tfirstName\x18\x03 \x01(\t\x12\x10\n\x08lastName\x18\x04 \x01(\t2Q\n\x08\x45mployee\x12\x45\n\ngetDetails\x12\x19.employee.EmployeeRequest\x1a\x1a.employee.EmployeeResponse\"\x00\x62\x06proto3'
)




_EMPLOYEEREQUEST = _descriptor.Descriptor(
  name='EmployeeRequest',
  full_name='employee.EmployeeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='employee.EmployeeRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=57,
)


_EMPLOYEERESPONSE = _descriptor.Descriptor(
  name='EmployeeResponse',
  full_name='employee.EmployeeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='employee.EmployeeResponse.message', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=121,
)


_EMPLOYEEDETAILS = _descriptor.Descriptor(
  name='EmployeeDetails',
  full_name='employee.EmployeeDetails',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='employee.EmployeeDetails.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='email', full_name='employee.EmployeeDetails.email', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='firstName', full_name='employee.EmployeeDetails.firstName', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lastName', full_name='employee.EmployeeDetails.lastName', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=123,
  serialized_end=204,
)

_EMPLOYEERESPONSE.fields_by_name['message'].message_type = _EMPLOYEEDETAILS
DESCRIPTOR.message_types_by_name['EmployeeRequest'] = _EMPLOYEEREQUEST
DESCRIPTOR.message_types_by_name['EmployeeResponse'] = _EMPLOYEERESPONSE
DESCRIPTOR.message_types_by_name['EmployeeDetails'] = _EMPLOYEEDETAILS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EmployeeRequest = _reflection.GeneratedProtocolMessageType('EmployeeRequest', (_message.Message,), {
  'DESCRIPTOR' : _EMPLOYEEREQUEST,
  '__module__' : 'employee_pb2'
  # @@protoc_insertion_point(class_scope:employee.EmployeeRequest)
  })
_sym_db.RegisterMessage(EmployeeRequest)

EmployeeResponse = _reflection.GeneratedProtocolMessageType('EmployeeResponse', (_message.Message,), {
  'DESCRIPTOR' : _EMPLOYEERESPONSE,
  '__module__' : 'employee_pb2'
  # @@protoc_insertion_point(class_scope:employee.EmployeeResponse)
  })
_sym_db.RegisterMessage(EmployeeResponse)

EmployeeDetails = _reflection.GeneratedProtocolMessageType('EmployeeDetails', (_message.Message,), {
  'DESCRIPTOR' : _EMPLOYEEDETAILS,
  '__module__' : 'employee_pb2'
  # @@protoc_insertion_point(class_scope:employee.EmployeeDetails)
  })
_sym_db.RegisterMessage(EmployeeDetails)



_EMPLOYEE = _descriptor.ServiceDescriptor(
  name='Employee',
  full_name='employee.Employee',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=206,
  serialized_end=287,
  methods=[
  _descriptor.MethodDescriptor(
    name='getDetails',
    full_name='employee.Employee.getDetails',
    index=0,
    containing_service=None,
    input_type=_EMPLOYEEREQUEST,
    output_type=_EMPLOYEERESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_EMPLOYEE)

DESCRIPTOR.services_by_name['Employee'] = _EMPLOYEE

# @@protoc_insertion_point(module_scope)
