# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: example.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='example.proto',
  package='example.proto',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n\rexample.proto\x12\rexample.proto\"\x1f\n\x0bProgramming\x12\x10\n\x08language\x18\x01 \x02(\t\"Y\n\x05\x45vent\x12\x0f\n\x07message\x18\x01 \x01(\t\x12,\n\x08language\x18\x02 \x03(\x0b\x32\x1a.example.proto.Programming\x12\x11\n\ttimestamp\x18\x03 \x01(\x04'
)




_PROGRAMMING = _descriptor.Descriptor(
  name='Programming',
  full_name='example.proto.Programming',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='language', full_name='example.proto.Programming.language', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=63,
)


_EVENT = _descriptor.Descriptor(
  name='Event',
  full_name='example.proto.Event',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='example.proto.Event.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='language', full_name='example.proto.Event.language', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='example.proto.Event.timestamp', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=154,
)

_EVENT.fields_by_name['language'].message_type = _PROGRAMMING
DESCRIPTOR.message_types_by_name['Programming'] = _PROGRAMMING
DESCRIPTOR.message_types_by_name['Event'] = _EVENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Programming = _reflection.GeneratedProtocolMessageType('Programming', (_message.Message,), {
  'DESCRIPTOR' : _PROGRAMMING,
  '__module__' : 'example_pb2'
  # @@protoc_insertion_point(class_scope:example.proto.Programming)
  })
_sym_db.RegisterMessage(Programming)

Event = _reflection.GeneratedProtocolMessageType('Event', (_message.Message,), {
  'DESCRIPTOR' : _EVENT,
  '__module__' : 'example_pb2'
  # @@protoc_insertion_point(class_scope:example.proto.Event)
  })
_sym_db.RegisterMessage(Event)


# @@protoc_insertion_point(module_scope)
