# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fight.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='fight.proto',
  package='msg',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0b\x66ight.proto\x12\x03msg\"0\n\nStartFight\x12\x11\n\terrorCode\x18\x01 \x01(\x05\x12\x0f\n\x07version\x18\x02 \x01(\x02\",\n\x0b\x46ightResult\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"+\n\nEnterFight\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\tb\x06proto3'
)




_STARTFIGHT = _descriptor.Descriptor(
  name='StartFight',
  full_name='msg.StartFight',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='errorCode', full_name='msg.StartFight.errorCode', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='version', full_name='msg.StartFight.version', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=68,
)


_FIGHTRESULT = _descriptor.Descriptor(
  name='FightResult',
  full_name='msg.FightResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='msg.FightResult.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='content', full_name='msg.FightResult.content', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=114,
)


_ENTERFIGHT = _descriptor.Descriptor(
  name='EnterFight',
  full_name='msg.EnterFight',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='msg.EnterFight.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='content', full_name='msg.EnterFight.content', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=116,
  serialized_end=159,
)

DESCRIPTOR.message_types_by_name['StartFight'] = _STARTFIGHT
DESCRIPTOR.message_types_by_name['FightResult'] = _FIGHTRESULT
DESCRIPTOR.message_types_by_name['EnterFight'] = _ENTERFIGHT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StartFight = _reflection.GeneratedProtocolMessageType('StartFight', (_message.Message,), {
  'DESCRIPTOR' : _STARTFIGHT,
  '__module__' : 'fight_pb2'
  # @@protoc_insertion_point(class_scope:msg.StartFight)
  })
_sym_db.RegisterMessage(StartFight)

FightResult = _reflection.GeneratedProtocolMessageType('FightResult', (_message.Message,), {
  'DESCRIPTOR' : _FIGHTRESULT,
  '__module__' : 'fight_pb2'
  # @@protoc_insertion_point(class_scope:msg.FightResult)
  })
_sym_db.RegisterMessage(FightResult)

EnterFight = _reflection.GeneratedProtocolMessageType('EnterFight', (_message.Message,), {
  'DESCRIPTOR' : _ENTERFIGHT,
  '__module__' : 'fight_pb2'
  # @@protoc_insertion_point(class_scope:msg.EnterFight)
  })
_sym_db.RegisterMessage(EnterFight)


# @@protoc_insertion_point(module_scope)
