# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: geolocation.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='geolocation.proto',
  package='geo',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n\x11geolocation.proto\x12\x03geo\"7\n\x0bGeoLocation\x12\x0e\n\x06\x64\x65vice\x18\x01 \x02(\x05\x12\x0b\n\x03lat\x18\x02 \x02(\x02\x12\x0b\n\x03lng\x18\x03 \x02(\x02'
)




_GEOLOCATION = _descriptor.Descriptor(
  name='GeoLocation',
  full_name='geo.GeoLocation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='device', full_name='geo.GeoLocation.device', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lat', full_name='geo.GeoLocation.lat', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lng', full_name='geo.GeoLocation.lng', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=81,
)

DESCRIPTOR.message_types_by_name['GeoLocation'] = _GEOLOCATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GeoLocation = _reflection.GeneratedProtocolMessageType('GeoLocation', (_message.Message,), {
  'DESCRIPTOR' : _GEOLOCATION,
  '__module__' : 'geolocation_pb2'
  # @@protoc_insertion_point(class_scope:geo.GeoLocation)
  })
_sym_db.RegisterMessage(GeoLocation)


# @@protoc_insertion_point(module_scope)
