# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GroundData.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import GpsLocation_pb2 as GpsLocation__pb2
import SensorData_pb2 as SensorData__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='GroundData.proto',
  package='xebia',
  syntax='proto3',
  serialized_options=b'\n\030com.xebia.protobuf.protoB\020GroundDataProtos',
  serialized_pb=b'\n\x10GroundData.proto\x12\x05xebia\x1a\x11GpsLocation.proto\x1a\x10SensorData.proto\"|\n\nGroundData\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x11\n\ttimestamp\x18\x02 \x01(\x05\x12\'\n\x0bgpsLocation\x18\x03 \x01(\x0b\x32\x12.xebia.GpsLocation\x12&\n\x0bsensorDatas\x18\x04 \x03(\x0b\x32\x11.xebia.SensorDataB,\n\x18\x63om.xebia.protobuf.protoB\x10GroundDataProtosb\x06proto3'
  ,
  dependencies=[GpsLocation__pb2.DESCRIPTOR,SensorData__pb2.DESCRIPTOR,])




_GROUNDDATA = _descriptor.Descriptor(
  name='GroundData',
  full_name='xebia.GroundData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='xebia.GroundData.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='xebia.GroundData.timestamp', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gpsLocation', full_name='xebia.GroundData.gpsLocation', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sensorDatas', full_name='xebia.GroundData.sensorDatas', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=64,
  serialized_end=188,
)

_GROUNDDATA.fields_by_name['gpsLocation'].message_type = GpsLocation__pb2._GPSLOCATION
_GROUNDDATA.fields_by_name['sensorDatas'].message_type = SensorData__pb2._SENSORDATA
DESCRIPTOR.message_types_by_name['GroundData'] = _GROUNDDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GroundData = _reflection.GeneratedProtocolMessageType('GroundData', (_message.Message,), {
  'DESCRIPTOR' : _GROUNDDATA,
  '__module__' : 'GroundData_pb2'
  # @@protoc_insertion_point(class_scope:xebia.GroundData)
  })
_sym_db.RegisterMessage(GroundData)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
