# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hello.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='hello.proto',
  package='hello',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n\x0bhello.proto\x12\x05hello\"1\n\nHelloWorld\x12\t\n\x01x\x18\x01 \x02(\x05\x12\t\n\x01y\x18\x02 \x02(\x05\x12\r\n\x05valid\x18\x03 \x01(\x05\"3\n\nHelloArray\x12%\n\nhelloWorld\x18\x01 \x03(\x0b\x32\x11.hello.HelloWorld'
)




_HELLOWORLD = _descriptor.Descriptor(
  name='HelloWorld',
  full_name='hello.HelloWorld',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='hello.HelloWorld.x', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='hello.HelloWorld.y', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='valid', full_name='hello.HelloWorld.valid', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=71,
)


_HELLOARRAY = _descriptor.Descriptor(
  name='HelloArray',
  full_name='hello.HelloArray',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='helloWorld', full_name='hello.HelloArray.helloWorld', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=124,
)

_HELLOARRAY.fields_by_name['helloWorld'].message_type = _HELLOWORLD
DESCRIPTOR.message_types_by_name['HelloWorld'] = _HELLOWORLD
DESCRIPTOR.message_types_by_name['HelloArray'] = _HELLOARRAY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HelloWorld = _reflection.GeneratedProtocolMessageType('HelloWorld', (_message.Message,), {
  'DESCRIPTOR' : _HELLOWORLD,
  '__module__' : 'hello_pb2'
  # @@protoc_insertion_point(class_scope:hello.HelloWorld)
  })
_sym_db.RegisterMessage(HelloWorld)

HelloArray = _reflection.GeneratedProtocolMessageType('HelloArray', (_message.Message,), {
  'DESCRIPTOR' : _HELLOARRAY,
  '__module__' : 'hello_pb2'
  # @@protoc_insertion_point(class_scope:hello.HelloArray)
  })
_sym_db.RegisterMessage(HelloArray)


# @@protoc_insertion_point(module_scope)
