# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: innerMap.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='innerMap.proto',
  package='innerMap',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0einnerMap.proto\x12\x08innerMap\"c\n\x03Map\x12\x1e\n\x05\x66loor\x18\x01 \x03(\x0b\x32\x0f.innerMap.Floor\x12\x1c\n\x04\x66ill\x18\x02 \x03(\x0b\x32\x0e.innerMap.Fill\x12\x1e\n\x05label\x18\x03 \x03(\x0b\x32\x0f.innerMap.Label\"W\n\x05\x46loor\x12$\n\x08geometry\x18\x01 \x03(\x0b\x32\x12.innerMap.Geometry\x12(\n\nproperties\x18\x02 \x03(\x0b\x32\x14.innerMap.Properties\"V\n\x04\x46ill\x12$\n\x08geometry\x18\x01 \x03(\x0b\x32\x12.innerMap.Geometry\x12(\n\nproperties\x18\x02 \x03(\x0b\x32\x14.innerMap.Properties\"W\n\x05Label\x12$\n\x08geometry\x18\x01 \x03(\x0b\x32\x12.innerMap.Geometry\x12(\n\nproperties\x18\x02 \x03(\x0b\x32\x14.innerMap.Properties\"-\n\x08Geometry\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x13\n\x0b\x63oordinates\x18\x02 \x03(\x01\"\xbb\x01\n\nProperties\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04icon\x18\x03 \x01(\t\x12\t\n\x01x\x18\x04 \x01(\x01\x12\t\n\x01y\x18\x05 \x01(\x01\x12\r\n\x05\x66loor\x18\x06 \x01(\x03\x12\x0e\n\x06height\x18\x07 \x01(\x03\x12\x0c\n\x04\x62\x61se\x18\x08 \x01(\t\x12\r\n\x05\x63olor\x18\t \x01(\t\x12\x0f\n\x07opacity\x18\n \x01(\x02\x12\x13\n\x0b\x62orderColor\x18\x0b \x01(\t\x12\r\n\x05layer\x18\x0c \x01(\x02\x62\x06proto3'
)




_MAP = _descriptor.Descriptor(
  name='Map',
  full_name='innerMap.Map',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='floor', full_name='innerMap.Map.floor', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fill', full_name='innerMap.Map.fill', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='label', full_name='innerMap.Map.label', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=127,
)


_FLOOR = _descriptor.Descriptor(
  name='Floor',
  full_name='innerMap.Floor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='geometry', full_name='innerMap.Floor.geometry', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='properties', full_name='innerMap.Floor.properties', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=129,
  serialized_end=216,
)


_FILL = _descriptor.Descriptor(
  name='Fill',
  full_name='innerMap.Fill',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='geometry', full_name='innerMap.Fill.geometry', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='properties', full_name='innerMap.Fill.properties', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=218,
  serialized_end=304,
)


_LABEL = _descriptor.Descriptor(
  name='Label',
  full_name='innerMap.Label',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='geometry', full_name='innerMap.Label.geometry', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='properties', full_name='innerMap.Label.properties', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=306,
  serialized_end=393,
)


_GEOMETRY = _descriptor.Descriptor(
  name='Geometry',
  full_name='innerMap.Geometry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='innerMap.Geometry.type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='coordinates', full_name='innerMap.Geometry.coordinates', index=1,
      number=2, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=395,
  serialized_end=440,
)


_PROPERTIES = _descriptor.Descriptor(
  name='Properties',
  full_name='innerMap.Properties',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='innerMap.Properties.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='innerMap.Properties.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='icon', full_name='innerMap.Properties.icon', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='x', full_name='innerMap.Properties.x', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='innerMap.Properties.y', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='floor', full_name='innerMap.Properties.floor', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='innerMap.Properties.height', index=6,
      number=7, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='base', full_name='innerMap.Properties.base', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='color', full_name='innerMap.Properties.color', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='opacity', full_name='innerMap.Properties.opacity', index=9,
      number=10, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='borderColor', full_name='innerMap.Properties.borderColor', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='layer', full_name='innerMap.Properties.layer', index=11,
      number=12, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=443,
  serialized_end=630,
)

_MAP.fields_by_name['floor'].message_type = _FLOOR
_MAP.fields_by_name['fill'].message_type = _FILL
_MAP.fields_by_name['label'].message_type = _LABEL
_FLOOR.fields_by_name['geometry'].message_type = _GEOMETRY
_FLOOR.fields_by_name['properties'].message_type = _PROPERTIES
_FILL.fields_by_name['geometry'].message_type = _GEOMETRY
_FILL.fields_by_name['properties'].message_type = _PROPERTIES
_LABEL.fields_by_name['geometry'].message_type = _GEOMETRY
_LABEL.fields_by_name['properties'].message_type = _PROPERTIES
DESCRIPTOR.message_types_by_name['Map'] = _MAP
DESCRIPTOR.message_types_by_name['Floor'] = _FLOOR
DESCRIPTOR.message_types_by_name['Fill'] = _FILL
DESCRIPTOR.message_types_by_name['Label'] = _LABEL
DESCRIPTOR.message_types_by_name['Geometry'] = _GEOMETRY
DESCRIPTOR.message_types_by_name['Properties'] = _PROPERTIES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Map = _reflection.GeneratedProtocolMessageType('Map', (_message.Message,), {
  'DESCRIPTOR' : _MAP,
  '__module__' : 'innerMap_pb2'
  # @@protoc_insertion_point(class_scope:innerMap.Map)
  })
_sym_db.RegisterMessage(Map)

Floor = _reflection.GeneratedProtocolMessageType('Floor', (_message.Message,), {
  'DESCRIPTOR' : _FLOOR,
  '__module__' : 'innerMap_pb2'
  # @@protoc_insertion_point(class_scope:innerMap.Floor)
  })
_sym_db.RegisterMessage(Floor)

Fill = _reflection.GeneratedProtocolMessageType('Fill', (_message.Message,), {
  'DESCRIPTOR' : _FILL,
  '__module__' : 'innerMap_pb2'
  # @@protoc_insertion_point(class_scope:innerMap.Fill)
  })
_sym_db.RegisterMessage(Fill)

Label = _reflection.GeneratedProtocolMessageType('Label', (_message.Message,), {
  'DESCRIPTOR' : _LABEL,
  '__module__' : 'innerMap_pb2'
  # @@protoc_insertion_point(class_scope:innerMap.Label)
  })
_sym_db.RegisterMessage(Label)

Geometry = _reflection.GeneratedProtocolMessageType('Geometry', (_message.Message,), {
  'DESCRIPTOR' : _GEOMETRY,
  '__module__' : 'innerMap_pb2'
  # @@protoc_insertion_point(class_scope:innerMap.Geometry)
  })
_sym_db.RegisterMessage(Geometry)

Properties = _reflection.GeneratedProtocolMessageType('Properties', (_message.Message,), {
  'DESCRIPTOR' : _PROPERTIES,
  '__module__' : 'innerMap_pb2'
  # @@protoc_insertion_point(class_scope:innerMap.Properties)
  })
_sym_db.RegisterMessage(Properties)


# @@protoc_insertion_point(module_scope)
