# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: KVCommand.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='KVCommand.proto',
  package='',
  syntax='proto2',
  serialized_options=b'\n\016net.demo.protoB\tKVCommand',
  serialized_pb=b'\n\x0fKVCommand.proto\"`\n\tKVMessage\x12\n\n\x02id\x18\x01 \x02(\r\x12\x0b\n\x03len\x18\x02 \x02(\r\x12\x1b\n\x07request\x18\x03 \x01(\x0b\x32\n.KVRequest\x12\x1d\n\x08response\x18\x04 \x01(\x0b\x32\x0b.KVResponse\"-\n\nKVResponse\x12\x0e\n\x06status\x18\x01 \x02(\r\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x8b\x01\n\tKVRequest\x12*\n\x04type\x18\x01 \x02(\x0e\x32\x16.KVRequest.RequestType:\x04ITEM\x12\x15\n\x04item\x18\x02 \x01(\x0b\x32\x07.KVItem\x12\x17\n\x05login\x18\x03 \x01(\x0b\x32\x08.KVLogin\"\"\n\x0bRequestType\x12\x08\n\x04ITEM\x10\x00\x12\t\n\x05LOGIN\x10\x01\"\x19\n\x06KVItem\x12\x0f\n\x07\x63ommand\x18\x01 \x02(\t\"-\n\x07KVLogin\x12\x10\n\x08username\x18\x01 \x02(\t\x12\x10\n\x08password\x18\x02 \x02(\tB\x1b\n\x0enet.demo.protoB\tKVCommand'
)



_KVREQUEST_REQUESTTYPE = _descriptor.EnumDescriptor(
  name='RequestType',
  full_name='KVRequest.RequestType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ITEM', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LOGIN', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=270,
  serialized_end=304,
)
_sym_db.RegisterEnumDescriptor(_KVREQUEST_REQUESTTYPE)


_KVMESSAGE = _descriptor.Descriptor(
  name='KVMessage',
  full_name='KVMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='KVMessage.id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='len', full_name='KVMessage.len', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='request', full_name='KVMessage.request', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='response', full_name='KVMessage.response', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=115,
)


_KVRESPONSE = _descriptor.Descriptor(
  name='KVResponse',
  full_name='KVResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='KVResponse.status', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='KVResponse.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=117,
  serialized_end=162,
)


_KVREQUEST = _descriptor.Descriptor(
  name='KVRequest',
  full_name='KVRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='KVRequest.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='item', full_name='KVRequest.item', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='login', full_name='KVRequest.login', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _KVREQUEST_REQUESTTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=165,
  serialized_end=304,
)


_KVITEM = _descriptor.Descriptor(
  name='KVItem',
  full_name='KVItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='command', full_name='KVItem.command', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=306,
  serialized_end=331,
)


_KVLOGIN = _descriptor.Descriptor(
  name='KVLogin',
  full_name='KVLogin',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='KVLogin.username', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='password', full_name='KVLogin.password', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=333,
  serialized_end=378,
)

_KVMESSAGE.fields_by_name['request'].message_type = _KVREQUEST
_KVMESSAGE.fields_by_name['response'].message_type = _KVRESPONSE
_KVREQUEST.fields_by_name['type'].enum_type = _KVREQUEST_REQUESTTYPE
_KVREQUEST.fields_by_name['item'].message_type = _KVITEM
_KVREQUEST.fields_by_name['login'].message_type = _KVLOGIN
_KVREQUEST_REQUESTTYPE.containing_type = _KVREQUEST
DESCRIPTOR.message_types_by_name['KVMessage'] = _KVMESSAGE
DESCRIPTOR.message_types_by_name['KVResponse'] = _KVRESPONSE
DESCRIPTOR.message_types_by_name['KVRequest'] = _KVREQUEST
DESCRIPTOR.message_types_by_name['KVItem'] = _KVITEM
DESCRIPTOR.message_types_by_name['KVLogin'] = _KVLOGIN
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

KVMessage = _reflection.GeneratedProtocolMessageType('KVMessage', (_message.Message,), {
  'DESCRIPTOR' : _KVMESSAGE,
  '__module__' : 'KVCommand_pb2'
  # @@protoc_insertion_point(class_scope:KVMessage)
  })
_sym_db.RegisterMessage(KVMessage)

KVResponse = _reflection.GeneratedProtocolMessageType('KVResponse', (_message.Message,), {
  'DESCRIPTOR' : _KVRESPONSE,
  '__module__' : 'KVCommand_pb2'
  # @@protoc_insertion_point(class_scope:KVResponse)
  })
_sym_db.RegisterMessage(KVResponse)

KVRequest = _reflection.GeneratedProtocolMessageType('KVRequest', (_message.Message,), {
  'DESCRIPTOR' : _KVREQUEST,
  '__module__' : 'KVCommand_pb2'
  # @@protoc_insertion_point(class_scope:KVRequest)
  })
_sym_db.RegisterMessage(KVRequest)

KVItem = _reflection.GeneratedProtocolMessageType('KVItem', (_message.Message,), {
  'DESCRIPTOR' : _KVITEM,
  '__module__' : 'KVCommand_pb2'
  # @@protoc_insertion_point(class_scope:KVItem)
  })
_sym_db.RegisterMessage(KVItem)

KVLogin = _reflection.GeneratedProtocolMessageType('KVLogin', (_message.Message,), {
  'DESCRIPTOR' : _KVLOGIN,
  '__module__' : 'KVCommand_pb2'
  # @@protoc_insertion_point(class_scope:KVLogin)
  })
_sym_db.RegisterMessage(KVLogin)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
