# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Login.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Login.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n\x0bLogin.proto\"\xa3\x01\n\x0cPBLoginField\x12\x0e\n\x06userid\x18\x01 \x02(\r\x12\x12\n\nszusername\x18\x02 \x01(\t\x12\x11\n\tszaccount\x18\x03 \x01(\t\x12\x12\n\nszpassword\x18\x04 \x01(\t\x12\x10\n\x08remember\x18\x05 \x01(\x08\x12\x11\n\tautologin\x18\x06 \x01(\x08\x12\x0f\n\x07startup\x18\x07 \x01(\x08\x12\x12\n\nupdatetime\x18\x08 \x01(\r\"/\n\x0bPBLoginList\x12 \n\tloginlist\x18\x01 \x03(\x0b\x32\r.PBLoginField'
)




_PBLOGINFIELD = _descriptor.Descriptor(
  name='PBLoginField',
  full_name='PBLoginField',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='userid', full_name='PBLoginField.userid', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='szusername', full_name='PBLoginField.szusername', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='szaccount', full_name='PBLoginField.szaccount', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='szpassword', full_name='PBLoginField.szpassword', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='remember', full_name='PBLoginField.remember', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='autologin', full_name='PBLoginField.autologin', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='startup', full_name='PBLoginField.startup', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='updatetime', full_name='PBLoginField.updatetime', index=7,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=179,
)


_PBLOGINLIST = _descriptor.Descriptor(
  name='PBLoginList',
  full_name='PBLoginList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='loginlist', full_name='PBLoginList.loginlist', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=181,
  serialized_end=228,
)

_PBLOGINLIST.fields_by_name['loginlist'].message_type = _PBLOGINFIELD
DESCRIPTOR.message_types_by_name['PBLoginField'] = _PBLOGINFIELD
DESCRIPTOR.message_types_by_name['PBLoginList'] = _PBLOGINLIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PBLoginField = _reflection.GeneratedProtocolMessageType('PBLoginField', (_message.Message,), {
  'DESCRIPTOR' : _PBLOGINFIELD,
  '__module__' : 'Login_pb2'
  # @@protoc_insertion_point(class_scope:PBLoginField)
  })
_sym_db.RegisterMessage(PBLoginField)

PBLoginList = _reflection.GeneratedProtocolMessageType('PBLoginList', (_message.Message,), {
  'DESCRIPTOR' : _PBLOGINLIST,
  '__module__' : 'Login_pb2'
  # @@protoc_insertion_point(class_scope:PBLoginList)
  })
_sym_db.RegisterMessage(PBLoginList)


# @@protoc_insertion_point(module_scope)
