# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lona.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='lona.proto',
  package='icd',
  syntax='proto2',
  serialized_options=b'\n\035com.boo.icdserialisation.lona',
  serialized_pb=b'\n\nlona.proto\x12\x03icd\"U\n\tLonaEvent\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07gps_lat\x18\x02 \x01(\x05\x12\x0f\n\x07gps_lon\x18\x03 \x01(\x05\x12\x18\n\x10server_timestamp\x18\x04 \x01(\x01\x42\x1f\n\x1d\x63om.boo.icdserialisation.lona'
)




_LONAEVENT = _descriptor.Descriptor(
  name='LonaEvent',
  full_name='icd.LonaEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='icd.LonaEvent.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gps_lat', full_name='icd.LonaEvent.gps_lat', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gps_lon', full_name='icd.LonaEvent.gps_lon', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='server_timestamp', full_name='icd.LonaEvent.server_timestamp', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=104,
)

DESCRIPTOR.message_types_by_name['LonaEvent'] = _LONAEVENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LonaEvent = _reflection.GeneratedProtocolMessageType('LonaEvent', (_message.Message,), {
  'DESCRIPTOR' : _LONAEVENT,
  '__module__' : 'lona_pb2'
  # @@protoc_insertion_point(class_scope:icd.LonaEvent)
  })
_sym_db.RegisterMessage(LonaEvent)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
