# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: maps.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='maps.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\nmaps.proto\"2\n\x12GetDistanceRequest\x12\x0e\n\x06origin\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x65st\x18\x02 \x01(\t\"\'\n\x13GetDistanceResponse\x12\x10\n\x08\x64istance\x18\x01 \x01(\x03\x32@\n\x04Maps\x12\x38\n\x0bGetDistance\x12\x13.GetDistanceRequest\x1a\x14.GetDistanceResponseb\x06proto3'
)




_GETDISTANCEREQUEST = _descriptor.Descriptor(
  name='GetDistanceRequest',
  full_name='GetDistanceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='origin', full_name='GetDistanceRequest.origin', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dest', full_name='GetDistanceRequest.dest', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=64,
)


_GETDISTANCERESPONSE = _descriptor.Descriptor(
  name='GetDistanceResponse',
  full_name='GetDistanceResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='distance', full_name='GetDistanceResponse.distance', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=105,
)

DESCRIPTOR.message_types_by_name['GetDistanceRequest'] = _GETDISTANCEREQUEST
DESCRIPTOR.message_types_by_name['GetDistanceResponse'] = _GETDISTANCERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetDistanceRequest = _reflection.GeneratedProtocolMessageType('GetDistanceRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETDISTANCEREQUEST,
  '__module__' : 'maps_pb2'
  # @@protoc_insertion_point(class_scope:GetDistanceRequest)
  })
_sym_db.RegisterMessage(GetDistanceRequest)

GetDistanceResponse = _reflection.GeneratedProtocolMessageType('GetDistanceResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETDISTANCERESPONSE,
  '__module__' : 'maps_pb2'
  # @@protoc_insertion_point(class_scope:GetDistanceResponse)
  })
_sym_db.RegisterMessage(GetDistanceResponse)



_MAPS = _descriptor.ServiceDescriptor(
  name='Maps',
  full_name='Maps',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=107,
  serialized_end=171,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetDistance',
    full_name='Maps.GetDistance',
    index=0,
    containing_service=None,
    input_type=_GETDISTANCEREQUEST,
    output_type=_GETDISTANCERESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MAPS)

DESCRIPTOR.services_by_name['Maps'] = _MAPS

# @@protoc_insertion_point(module_scope)
