# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MessageData.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='MessageData.proto',
  package='com.pinkpig.entity.protobuf',
  syntax='proto3',
  serialized_options=b'B\014MessageProto',
  serialized_pb=b'\n\x11MessageData.proto\x12\x1b\x63om.pinkpig.entity.protobuf\"Y\n\x0bMessageData\x12\x39\n\tsysHeader\x18\x01 \x01(\x0b\x32&.com.pinkpig.entity.protobuf.SysHeader\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\x0c\"\x95\x01\n\tSysHeader\x12\x10\n\x08\x62izSeqNo\x18\x01 \x01(\t\x12\x10\n\x08sysSeqNo\x18\x02 \x01(\t\x12\n\n\x02ip\x18\x03 \x01(\t\x12\x0e\n\x06userId\x18\x04 \x01(\t\x12\x0f\n\x07version\x18\x05 \x01(\x05\x12\x11\n\tchannelId\x18\x06 \x01(\t\x12\x11\n\torigSysId\x18\x07 \x01(\t\x12\x11\n\tprevSysId\x18\x08 \x01(\tB\x0e\x42\x0cMessageProtob\x06proto3'
)




_MESSAGEDATA = _descriptor.Descriptor(
  name='MessageData',
  full_name='com.pinkpig.entity.protobuf.MessageData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sysHeader', full_name='com.pinkpig.entity.protobuf.MessageData.sysHeader', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='content', full_name='com.pinkpig.entity.protobuf.MessageData.content', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=139,
)


_SYSHEADER = _descriptor.Descriptor(
  name='SysHeader',
  full_name='com.pinkpig.entity.protobuf.SysHeader',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bizSeqNo', full_name='com.pinkpig.entity.protobuf.SysHeader.bizSeqNo', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sysSeqNo', full_name='com.pinkpig.entity.protobuf.SysHeader.sysSeqNo', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ip', full_name='com.pinkpig.entity.protobuf.SysHeader.ip', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='userId', full_name='com.pinkpig.entity.protobuf.SysHeader.userId', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='version', full_name='com.pinkpig.entity.protobuf.SysHeader.version', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='channelId', full_name='com.pinkpig.entity.protobuf.SysHeader.channelId', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='origSysId', full_name='com.pinkpig.entity.protobuf.SysHeader.origSysId', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='prevSysId', full_name='com.pinkpig.entity.protobuf.SysHeader.prevSysId', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=142,
  serialized_end=291,
)

_MESSAGEDATA.fields_by_name['sysHeader'].message_type = _SYSHEADER
DESCRIPTOR.message_types_by_name['MessageData'] = _MESSAGEDATA
DESCRIPTOR.message_types_by_name['SysHeader'] = _SYSHEADER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MessageData = _reflection.GeneratedProtocolMessageType('MessageData', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGEDATA,
  '__module__' : 'MessageData_pb2'
  # @@protoc_insertion_point(class_scope:com.pinkpig.entity.protobuf.MessageData)
  })
_sym_db.RegisterMessage(MessageData)

SysHeader = _reflection.GeneratedProtocolMessageType('SysHeader', (_message.Message,), {
  'DESCRIPTOR' : _SYSHEADER,
  '__module__' : 'MessageData_pb2'
  # @@protoc_insertion_point(class_scope:com.pinkpig.entity.protobuf.SysHeader)
  })
_sym_db.RegisterMessage(SysHeader)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
