# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='msg.proto',
  package='msg',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\tmsg.proto\x12\x03msg\"6\n\x04Msg1\x12\x0e\n\x06\x66ield1\x18\x01 \x01(\t\x12\x0e\n\x06\x66ield2\x18\x02 \x01(\x05\x12\x0e\n\x06\x66ield3\x18\x03 \x01(\t\"6\n\x04Msg2\x12\x0e\n\x06\x66ield4\x18\x01 \x01(\x05\x12\x0e\n\x06\x66ield5\x18\x02 \x01(\t\x12\x0e\n\x06\x66ield6\x18\x03 \x01(\tb\x06proto3'
)




_MSG1 = _descriptor.Descriptor(
  name='Msg1',
  full_name='msg.Msg1',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='field1', full_name='msg.Msg1.field1', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='field2', full_name='msg.Msg1.field2', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='field3', full_name='msg.Msg1.field3', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=72,
)


_MSG2 = _descriptor.Descriptor(
  name='Msg2',
  full_name='msg.Msg2',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='field4', full_name='msg.Msg2.field4', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='field5', full_name='msg.Msg2.field5', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='field6', full_name='msg.Msg2.field6', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=128,
)

DESCRIPTOR.message_types_by_name['Msg1'] = _MSG1
DESCRIPTOR.message_types_by_name['Msg2'] = _MSG2
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Msg1 = _reflection.GeneratedProtocolMessageType('Msg1', (_message.Message,), {
  'DESCRIPTOR' : _MSG1,
  '__module__' : 'msg_pb2'
  # @@protoc_insertion_point(class_scope:msg.Msg1)
  })
_sym_db.RegisterMessage(Msg1)

Msg2 = _reflection.GeneratedProtocolMessageType('Msg2', (_message.Message,), {
  'DESCRIPTOR' : _MSG2,
  '__module__' : 'msg_pb2'
  # @@protoc_insertion_point(class_scope:msg.Msg2)
  })
_sym_db.RegisterMessage(Msg2)


# @@protoc_insertion_point(module_scope)
