# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msginfo.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='msginfo.proto',
  package='msginfo',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n\rmsginfo.proto\x12\x07msginfo\"(\n\x04\x43Msg\x12\x0f\n\x07msghead\x18\x01 \x02(\t\x12\x0f\n\x07msgbody\x18\x02 \x02(\t\"p\n\x08\x43MsgHead\x12\x0e\n\x06msglen\x18\x01 \x02(\x05\x12\x0f\n\x07msgtype\x18\x02 \x02(\x05\x12\x0e\n\x06msgseq\x18\x03 \x02(\x05\x12\x13\n\x0btermversion\x18\x04 \x02(\x05\x12\x0e\n\x06msgres\x18\x05 \x02(\x05\x12\x0e\n\x06termid\x18\x06 \x02(\t\"Y\n\x07\x43MsgReg\x12\x0c\n\x04\x61rea\x18\x01 \x01(\x05\x12\x0e\n\x06region\x18\x02 \x01(\x05\x12\x0c\n\x04shop\x18\x03 \x01(\x05\x12\x0b\n\x03ret\x18\x04 \x01(\x05\x12\x15\n\x06termid\x18\x05 \x01(\t:\x05\x31\x32\x33\x34\x35\"\x18\n\tCMsgLogin\x12\x0b\n\x03ret\x18\x01 \x01(\x05\"\x19\n\nCMsgLogout\x12\x0b\n\x03ret\x18\x01 \x01(\x05'
)




_CMSG = _descriptor.Descriptor(
  name='CMsg',
  full_name='msginfo.CMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msghead', full_name='msginfo.CMsg.msghead', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msgbody', full_name='msginfo.CMsg.msgbody', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=66,
)


_CMSGHEAD = _descriptor.Descriptor(
  name='CMsgHead',
  full_name='msginfo.CMsgHead',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msglen', full_name='msginfo.CMsgHead.msglen', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msgtype', full_name='msginfo.CMsgHead.msgtype', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msgseq', full_name='msginfo.CMsgHead.msgseq', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='termversion', full_name='msginfo.CMsgHead.termversion', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msgres', full_name='msginfo.CMsgHead.msgres', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='termid', full_name='msginfo.CMsgHead.termid', index=5,
      number=6, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=180,
)


_CMSGREG = _descriptor.Descriptor(
  name='CMsgReg',
  full_name='msginfo.CMsgReg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='area', full_name='msginfo.CMsgReg.area', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='region', full_name='msginfo.CMsgReg.region', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='shop', full_name='msginfo.CMsgReg.shop', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ret', full_name='msginfo.CMsgReg.ret', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='termid', full_name='msginfo.CMsgReg.termid', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=b"12345".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=182,
  serialized_end=271,
)


_CMSGLOGIN = _descriptor.Descriptor(
  name='CMsgLogin',
  full_name='msginfo.CMsgLogin',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ret', full_name='msginfo.CMsgLogin.ret', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=273,
  serialized_end=297,
)


_CMSGLOGOUT = _descriptor.Descriptor(
  name='CMsgLogout',
  full_name='msginfo.CMsgLogout',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ret', full_name='msginfo.CMsgLogout.ret', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=299,
  serialized_end=324,
)

DESCRIPTOR.message_types_by_name['CMsg'] = _CMSG
DESCRIPTOR.message_types_by_name['CMsgHead'] = _CMSGHEAD
DESCRIPTOR.message_types_by_name['CMsgReg'] = _CMSGREG
DESCRIPTOR.message_types_by_name['CMsgLogin'] = _CMSGLOGIN
DESCRIPTOR.message_types_by_name['CMsgLogout'] = _CMSGLOGOUT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CMsg = _reflection.GeneratedProtocolMessageType('CMsg', (_message.Message,), {
  'DESCRIPTOR' : _CMSG,
  '__module__' : 'msginfo_pb2'
  # @@protoc_insertion_point(class_scope:msginfo.CMsg)
  })
_sym_db.RegisterMessage(CMsg)

CMsgHead = _reflection.GeneratedProtocolMessageType('CMsgHead', (_message.Message,), {
  'DESCRIPTOR' : _CMSGHEAD,
  '__module__' : 'msginfo_pb2'
  # @@protoc_insertion_point(class_scope:msginfo.CMsgHead)
  })
_sym_db.RegisterMessage(CMsgHead)

CMsgReg = _reflection.GeneratedProtocolMessageType('CMsgReg', (_message.Message,), {
  'DESCRIPTOR' : _CMSGREG,
  '__module__' : 'msginfo_pb2'
  # @@protoc_insertion_point(class_scope:msginfo.CMsgReg)
  })
_sym_db.RegisterMessage(CMsgReg)

CMsgLogin = _reflection.GeneratedProtocolMessageType('CMsgLogin', (_message.Message,), {
  'DESCRIPTOR' : _CMSGLOGIN,
  '__module__' : 'msginfo_pb2'
  # @@protoc_insertion_point(class_scope:msginfo.CMsgLogin)
  })
_sym_db.RegisterMessage(CMsgLogin)

CMsgLogout = _reflection.GeneratedProtocolMessageType('CMsgLogout', (_message.Message,), {
  'DESCRIPTOR' : _CMSGLOGOUT,
  '__module__' : 'msginfo_pb2'
  # @@protoc_insertion_point(class_scope:msginfo.CMsgLogout)
  })
_sym_db.RegisterMessage(CMsgLogout)


# @@protoc_insertion_point(module_scope)
