# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: my-message.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='my-message.proto',
  package='org.hiatusuk.messages',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n\x10my-message.proto\x12\x15org.hiatusuk.messages\"\xba\x01\n\tMyMessage\x12\n\n\x02id\x18\x01 \x02(\x03\x12\r\n\x05\x65mail\x18\x02 \x02(\t\x12\x1d\n\x15userExternalReference\x18\x03 \x02(\t\x12\x37\n\x04role\x18\x04 \x01(\x0e\x32).org.hiatusuk.messages.MyMessage.UserRole\x12\x15\n\rcorrelationId\x18\x05 \x01(\t\"#\n\x08UserRole\x12\n\n\x06MASTER\x10\x01\x12\x0b\n\x07SERVANT\x10\x02'
)



_MYMESSAGE_USERROLE = _descriptor.EnumDescriptor(
  name='UserRole',
  full_name='org.hiatusuk.messages.MyMessage.UserRole',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MASTER', index=0, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SERVANT', index=1, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=195,
  serialized_end=230,
)
_sym_db.RegisterEnumDescriptor(_MYMESSAGE_USERROLE)


_MYMESSAGE = _descriptor.Descriptor(
  name='MyMessage',
  full_name='org.hiatusuk.messages.MyMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='org.hiatusuk.messages.MyMessage.id', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='email', full_name='org.hiatusuk.messages.MyMessage.email', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='userExternalReference', full_name='org.hiatusuk.messages.MyMessage.userExternalReference', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='role', full_name='org.hiatusuk.messages.MyMessage.role', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='correlationId', full_name='org.hiatusuk.messages.MyMessage.correlationId', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _MYMESSAGE_USERROLE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=230,
)

_MYMESSAGE.fields_by_name['role'].enum_type = _MYMESSAGE_USERROLE
_MYMESSAGE_USERROLE.containing_type = _MYMESSAGE
DESCRIPTOR.message_types_by_name['MyMessage'] = _MYMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MyMessage = _reflection.GeneratedProtocolMessageType('MyMessage', (_message.Message,), {
  'DESCRIPTOR' : _MYMESSAGE,
  '__module__' : 'my_message_pb2'
  # @@protoc_insertion_point(class_scope:org.hiatusuk.messages.MyMessage)
  })
_sym_db.RegisterMessage(MyMessage)


# @@protoc_insertion_point(module_scope)
