# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nested.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='nested.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0cnested.proto\"\xc4\x01\n\x08\x42uilding\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x16\n\x0e\x62uildingNumber\x18\x02 \x01(\t\x12 \n\x06street\x18\x03 \x01(\x0b\x32\x10.Building.Street\x1a\x34\n\x06Street\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x1c\n\x04\x63ity\x18\x02 \x01(\x0b\x32\x0e.Building.City\x1a:\n\x04\x43ity\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07zipCode\x18\x02 \x01(\t\x12\x13\n\x0b\x63ountryName\x18\x03 \x01(\tb\x06proto3'
)




_BUILDING_STREET = _descriptor.Descriptor(
  name='Street',
  full_name='Building.Street',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='Building.Street.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='city', full_name='Building.Street.city', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=101,
  serialized_end=153,
)

_BUILDING_CITY = _descriptor.Descriptor(
  name='City',
  full_name='Building.City',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='Building.City.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='zipCode', full_name='Building.City.zipCode', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='countryName', full_name='Building.City.countryName', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=155,
  serialized_end=213,
)

_BUILDING = _descriptor.Descriptor(
  name='Building',
  full_name='Building',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='Building.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='buildingNumber', full_name='Building.buildingNumber', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='street', full_name='Building.street', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_BUILDING_STREET, _BUILDING_CITY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=213,
)

_BUILDING_STREET.fields_by_name['city'].message_type = _BUILDING_CITY
_BUILDING_STREET.containing_type = _BUILDING
_BUILDING_CITY.containing_type = _BUILDING
_BUILDING.fields_by_name['street'].message_type = _BUILDING_STREET
DESCRIPTOR.message_types_by_name['Building'] = _BUILDING
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Building = _reflection.GeneratedProtocolMessageType('Building', (_message.Message,), {

  'Street' : _reflection.GeneratedProtocolMessageType('Street', (_message.Message,), {
    'DESCRIPTOR' : _BUILDING_STREET,
    '__module__' : 'nested_pb2'
    # @@protoc_insertion_point(class_scope:Building.Street)
    })
  ,

  'City' : _reflection.GeneratedProtocolMessageType('City', (_message.Message,), {
    'DESCRIPTOR' : _BUILDING_CITY,
    '__module__' : 'nested_pb2'
    # @@protoc_insertion_point(class_scope:Building.City)
    })
  ,
  'DESCRIPTOR' : _BUILDING,
  '__module__' : 'nested_pb2'
  # @@protoc_insertion_point(class_scope:Building)
  })
_sym_db.RegisterMessage(Building)
_sym_db.RegisterMessage(Building.Street)
_sym_db.RegisterMessage(Building.City)


# @@protoc_insertion_point(module_scope)
