# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: notification.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='notification.proto',
  package='com.example.research.kafkabootdemo',
  syntax='proto3',
  serialized_options=b'\n\030com.example.rabbitmqdemoB\022NotificationProtos',
  serialized_pb=b'\n\x12notification.proto\x12\"com.example.research.kafkabootdemo\"2\n\x0fNotificationDTO\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0e\n\x06sentAt\x18\x02 \x01(\tB.\n\x18\x63om.example.rabbitmqdemoB\x12NotificationProtosb\x06proto3'
)




_NOTIFICATIONDTO = _descriptor.Descriptor(
  name='NotificationDTO',
  full_name='com.example.research.kafkabootdemo.NotificationDTO',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='com.example.research.kafkabootdemo.NotificationDTO.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sentAt', full_name='com.example.research.kafkabootdemo.NotificationDTO.sentAt', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=108,
)

DESCRIPTOR.message_types_by_name['NotificationDTO'] = _NOTIFICATIONDTO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NotificationDTO = _reflection.GeneratedProtocolMessageType('NotificationDTO', (_message.Message,), {
  'DESCRIPTOR' : _NOTIFICATIONDTO,
  '__module__' : 'notification_pb2'
  # @@protoc_insertion_point(class_scope:com.example.research.kafkabootdemo.NotificationDTO)
  })
_sym_db.RegisterMessage(NotificationDTO)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
