# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PersonProto.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='PersonProto.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\n!com.jakepartusch.generated.domainB\020OuterPersonProtoP\001',
  serialized_pb=b'\n\x11PersonProto.proto\"\xc3\x01\n\x0bPersonProto\x12\x11\n\tfirstName\x18\x01 \x01(\t\x12\x10\n\x08lastName\x18\x02 \x01(\t\x12\x14\n\x0c\x65mailAddress\x18\x03 \x01(\t\x12\x13\n\x0bhomeAddress\x18\x04 \x01(\t\x12.\n\x0cphoneNumbers\x18\x05 \x03(\x0b\x32\x18.PersonProto.PhoneNumber\x1a\x34\n\x0bPhoneNumber\x12\x10\n\x08\x61reaCode\x18\x01 \x01(\x05\x12\x13\n\x0bphoneNumber\x18\x02 \x01(\x05\x42\x37\n!com.jakepartusch.generated.domainB\x10OuterPersonProtoP\x01\x62\x06proto3'
)




_PERSONPROTO_PHONENUMBER = _descriptor.Descriptor(
  name='PhoneNumber',
  full_name='PersonProto.PhoneNumber',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='areaCode', full_name='PersonProto.PhoneNumber.areaCode', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='phoneNumber', full_name='PersonProto.PhoneNumber.phoneNumber', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=165,
  serialized_end=217,
)

_PERSONPROTO = _descriptor.Descriptor(
  name='PersonProto',
  full_name='PersonProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='firstName', full_name='PersonProto.firstName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lastName', full_name='PersonProto.lastName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='emailAddress', full_name='PersonProto.emailAddress', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='homeAddress', full_name='PersonProto.homeAddress', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='phoneNumbers', full_name='PersonProto.phoneNumbers', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_PERSONPROTO_PHONENUMBER, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=217,
)

_PERSONPROTO_PHONENUMBER.containing_type = _PERSONPROTO
_PERSONPROTO.fields_by_name['phoneNumbers'].message_type = _PERSONPROTO_PHONENUMBER
DESCRIPTOR.message_types_by_name['PersonProto'] = _PERSONPROTO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PersonProto = _reflection.GeneratedProtocolMessageType('PersonProto', (_message.Message,), {

  'PhoneNumber' : _reflection.GeneratedProtocolMessageType('PhoneNumber', (_message.Message,), {
    'DESCRIPTOR' : _PERSONPROTO_PHONENUMBER,
    '__module__' : 'PersonProto_pb2'
    # @@protoc_insertion_point(class_scope:PersonProto.PhoneNumber)
    })
  ,
  'DESCRIPTOR' : _PERSONPROTO,
  '__module__' : 'PersonProto_pb2'
  # @@protoc_insertion_point(class_scope:PersonProto)
  })
_sym_db.RegisterMessage(PersonProto)
_sym_db.RegisterMessage(PersonProto.PhoneNumber)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
