# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PersonTest.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='PersonTest.proto',
  package='ProtoBufDemo',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n\x10PersonTest.proto\x12\x0cProtoBufDemo\"_\n\nPersonTest\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\n\n\x02id\x18\x02 \x02(\x05\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x0c\n\x04size\x18\x04 \x02(\t\x12\x0b\n\x03\x62uf\x18\x05 \x02(\x0c\x12\r\n\x05isimg\x18\x06 \x02(\x08'
)




_PERSONTEST = _descriptor.Descriptor(
  name='PersonTest',
  full_name='ProtoBufDemo.PersonTest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='ProtoBufDemo.PersonTest.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='ProtoBufDemo.PersonTest.id', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='email', full_name='ProtoBufDemo.PersonTest.email', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='size', full_name='ProtoBufDemo.PersonTest.size', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='buf', full_name='ProtoBufDemo.PersonTest.buf', index=4,
      number=5, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='isimg', full_name='ProtoBufDemo.PersonTest.isimg', index=5,
      number=6, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=129,
)

DESCRIPTOR.message_types_by_name['PersonTest'] = _PERSONTEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PersonTest = _reflection.GeneratedProtocolMessageType('PersonTest', (_message.Message,), {
  'DESCRIPTOR' : _PERSONTEST,
  '__module__' : 'PersonTest_pb2'
  # @@protoc_insertion_point(class_scope:ProtoBufDemo.PersonTest)
  })
_sym_db.RegisterMessage(PersonTest)


# @@protoc_insertion_point(module_scope)
