# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protodemo.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protodemo.proto',
  package='demo',
  syntax='proto2',
  serialized_options=b'\n\013sample.demoB\tProtoDemo',
  serialized_pb=b'\n\x0fprotodemo.proto\x12\x04\x64\x65mo\"\x95\x02\n\x07Student\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x0c\n\x04name\x18\x02 \x02(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12#\n\x03sex\x18\x04 \x01(\x0e\x32\x11.demo.Student.Sex:\x03MAN\x12(\n\x05phone\x18\x05 \x03(\x0b\x32\x19.demo.Student.PhoneNumber\x1aJ\n\x0bPhoneNumber\x12\x0e\n\x06number\x18\x01 \x02(\t\x12+\n\x04type\x18\x02 \x01(\x0e\x32\x17.demo.Student.PhoneType:\x04HOME\"\x19\n\x03Sex\x12\x07\n\x03MAN\x10\x00\x12\t\n\x05WOMAN\x10\x01\"+\n\tPhoneType\x12\n\n\x06MOBILE\x10\x00\x12\x08\n\x04HOME\x10\x01\x12\x08\n\x04WORK\x10\x02\x42\x18\n\x0bsample.demoB\tProtoDemo'
)



_STUDENT_SEX = _descriptor.EnumDescriptor(
  name='Sex',
  full_name='demo.Student.Sex',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MAN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WOMAN', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=233,
  serialized_end=258,
)
_sym_db.RegisterEnumDescriptor(_STUDENT_SEX)

_STUDENT_PHONETYPE = _descriptor.EnumDescriptor(
  name='PhoneType',
  full_name='demo.Student.PhoneType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MOBILE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HOME', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WORK', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=260,
  serialized_end=303,
)
_sym_db.RegisterEnumDescriptor(_STUDENT_PHONETYPE)


_STUDENT_PHONENUMBER = _descriptor.Descriptor(
  name='PhoneNumber',
  full_name='demo.Student.PhoneNumber',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='number', full_name='demo.Student.PhoneNumber.number', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='demo.Student.PhoneNumber.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=157,
  serialized_end=231,
)

_STUDENT = _descriptor.Descriptor(
  name='Student',
  full_name='demo.Student',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='demo.Student.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='demo.Student.name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='email', full_name='demo.Student.email', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sex', full_name='demo.Student.sex', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='phone', full_name='demo.Student.phone', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_STUDENT_PHONENUMBER, ],
  enum_types=[
    _STUDENT_SEX,
    _STUDENT_PHONETYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=303,
)

_STUDENT_PHONENUMBER.fields_by_name['type'].enum_type = _STUDENT_PHONETYPE
_STUDENT_PHONENUMBER.containing_type = _STUDENT
_STUDENT.fields_by_name['sex'].enum_type = _STUDENT_SEX
_STUDENT.fields_by_name['phone'].message_type = _STUDENT_PHONENUMBER
_STUDENT_SEX.containing_type = _STUDENT
_STUDENT_PHONETYPE.containing_type = _STUDENT
DESCRIPTOR.message_types_by_name['Student'] = _STUDENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Student = _reflection.GeneratedProtocolMessageType('Student', (_message.Message,), {

  'PhoneNumber' : _reflection.GeneratedProtocolMessageType('PhoneNumber', (_message.Message,), {
    'DESCRIPTOR' : _STUDENT_PHONENUMBER,
    '__module__' : 'protodemo_pb2'
    # @@protoc_insertion_point(class_scope:demo.Student.PhoneNumber)
    })
  ,
  'DESCRIPTOR' : _STUDENT,
  '__module__' : 'protodemo_pb2'
  # @@protoc_insertion_point(class_scope:demo.Student)
  })
_sym_db.RegisterMessage(Student)
_sym_db.RegisterMessage(Student.PhoneNumber)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
