# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: qwe.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='qwe.proto',
  package='main',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\tqwe.proto\x12\x04main\" \n\x03Qwe\x12\x0b\n\x03\x61ge\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\tb\x06proto3'
)




_QWE = _descriptor.Descriptor(
  name='Qwe',
  full_name='main.Qwe',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='age', full_name='main.Qwe.age', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='main.Qwe.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=51,
)

DESCRIPTOR.message_types_by_name['Qwe'] = _QWE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Qwe = _reflection.GeneratedProtocolMessageType('Qwe', (_message.Message,), {
  'DESCRIPTOR' : _QWE,
  '__module__' : 'qwe_pb2'
  # @@protoc_insertion_point(class_scope:main.Qwe)
  })
_sym_db.RegisterMessage(Qwe)


# @@protoc_insertion_point(module_scope)
