# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: socket.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='socket.proto',
  package='cover',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0csocket.proto\x12\x05\x63over\"6\n\x06Socket\x12\x15\n\rrequest_field\x18\x01 \x01(\t\x12\x15\n\rreceive_field\x18\x02 \x01(\tb\x06proto3'
)




_SOCKET = _descriptor.Descriptor(
  name='Socket',
  full_name='cover.Socket',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='request_field', full_name='cover.Socket.request_field', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='receive_field', full_name='cover.Socket.receive_field', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=77,
)

DESCRIPTOR.message_types_by_name['Socket'] = _SOCKET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Socket = _reflection.GeneratedProtocolMessageType('Socket', (_message.Message,), {
  'DESCRIPTOR' : _SOCKET,
  '__module__' : 'socket_pb2'
  # @@protoc_insertion_point(class_scope:cover.Socket)
  })
_sym_db.RegisterMessage(Socket)


# @@protoc_insertion_point(module_scope)
