# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: spirits.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='spirits.proto',
  package='gogrpc',
  syntax='proto3',
  serialized_options=b'Z\006gogrpc',
  serialized_pb=b'\n\rspirits.proto\x12\x06gogrpc\"\xe5\x02\n\x06Spirit\x12\n\n\x02Id\x18\x01 \x01(\t\x12\x0c\n\x04Name\x18\x02 \x01(\t\x12\x11\n\tDistiller\x18\x03 \x01(\t\x12\x0f\n\x07\x42ottler\x18\x04 \x01(\t\x12\x0f\n\x07\x43ountry\x18\x05 \x01(\t\x12\x0e\n\x06Region\x18\x06 \x01(\t\x12\x13\n\x0b\x43omposition\x18\x07 \x01(\t\x12\'\n\x04type\x18\x08 \x01(\x0e\x32\x19.gogrpc.Spirit.SpiritType\x12\x0b\n\x03\x41ge\x18\t \x01(\x05\x12\x14\n\x0c\x42ottlingDate\x18\n \x01(\x03\x12\r\n\x05Score\x18\x0b \x01(\x02\x12\x0f\n\x07\x43omment\x18\x0c \x01(\t\"{\n\nSpiritType\x12\x13\n\x0fTypeUnspecified\x10\x00\x12\x0c\n\x08TypeRhum\x10\x01\x12\x0c\n\x08TypeWine\x10\x02\x12\x0e\n\nTypeWhisky\x10\x03\x12\x11\n\rTypeChampagne\x10\x04\x12\x0b\n\x07TypeGin\x10\x05\x12\x0c\n\x08TypeBeer\x10\x06\"7\n\x15SpiritCreationRequest\x12\x1e\n\x06spirit\x18\x01 \x01(\x0b\x32\x0e.gogrpc.Spirit\"5\n\x13SpiritUpdateRequest\x12\x1e\n\x06spirit\x18\x01 \x01(\x0b\x32\x0e.gogrpc.Spirit\"5\n\x13SpiritDeleteRequest\x12\x1e\n\x06spirit\x18\x01 \x01(\x0b\x32\x0e.gogrpc.Spirit\"5\n\x13SpiritSearchRequest\x12\x1e\n\x06spirit\x18\x01 \x01(\x0b\x32\x0e.gogrpc.Spirit\"8\n\x16SpiritCreationResponse\x12\x1e\n\x06spirit\x18\x01 \x01(\x0b\x32\x0e.gogrpc.Spirit\"6\n\x14SpiritUpdateResponse\x12\x1e\n\x06spirit\x18\x01 \x01(\x0b\x32\x0e.gogrpc.Spirit\"\'\n\x14SpiritDeleteResponse\x12\x0f\n\x07\x64\x65leted\x18\x01 \x01(\x08\"6\n\x14SpiritSearchResponse\x12\x1e\n\x06spirit\x18\x01 \x03(\x0b\x32\x0e.gogrpc.Spirit2\xc9\x02\n\rSpiritService\x12O\n\x0c\x43reateSpirit\x12\x1d.gogrpc.SpiritCreationRequest\x1a\x1e.gogrpc.SpiritCreationResponse\"\x00\x12K\n\x0cUpdateSpirit\x12\x1b.gogrpc.SpiritUpdateRequest\x1a\x1c.gogrpc.SpiritUpdateResponse\"\x00\x12K\n\x0c\x44\x65leteSpirit\x12\x1b.gogrpc.SpiritDeleteRequest\x1a\x1c.gogrpc.SpiritDeleteResponse\"\x00\x12M\n\x0cSearchSpirit\x12\x1b.gogrpc.SpiritSearchRequest\x1a\x1c.gogrpc.SpiritSearchResponse\"\x00\x30\x01\x42\x08Z\x06gogrpcb\x06proto3'
)



_SPIRIT_SPIRITTYPE = _descriptor.EnumDescriptor(
  name='SpiritType',
  full_name='gogrpc.Spirit.SpiritType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TypeUnspecified', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TypeRhum', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TypeWine', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TypeWhisky', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TypeChampagne', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TypeGin', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TypeBeer', index=6, number=6,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=260,
  serialized_end=383,
)
_sym_db.RegisterEnumDescriptor(_SPIRIT_SPIRITTYPE)


_SPIRIT = _descriptor.Descriptor(
  name='Spirit',
  full_name='gogrpc.Spirit',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Id', full_name='gogrpc.Spirit.Id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Name', full_name='gogrpc.Spirit.Name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Distiller', full_name='gogrpc.Spirit.Distiller', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Bottler', full_name='gogrpc.Spirit.Bottler', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Country', full_name='gogrpc.Spirit.Country', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Region', full_name='gogrpc.Spirit.Region', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Composition', full_name='gogrpc.Spirit.Composition', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='gogrpc.Spirit.type', index=7,
      number=8, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Age', full_name='gogrpc.Spirit.Age', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='BottlingDate', full_name='gogrpc.Spirit.BottlingDate', index=9,
      number=10, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Score', full_name='gogrpc.Spirit.Score', index=10,
      number=11, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Comment', full_name='gogrpc.Spirit.Comment', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SPIRIT_SPIRITTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=383,
)


_SPIRITCREATIONREQUEST = _descriptor.Descriptor(
  name='SpiritCreationRequest',
  full_name='gogrpc.SpiritCreationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='spirit', full_name='gogrpc.SpiritCreationRequest.spirit', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=385,
  serialized_end=440,
)


_SPIRITUPDATEREQUEST = _descriptor.Descriptor(
  name='SpiritUpdateRequest',
  full_name='gogrpc.SpiritUpdateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='spirit', full_name='gogrpc.SpiritUpdateRequest.spirit', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=442,
  serialized_end=495,
)


_SPIRITDELETEREQUEST = _descriptor.Descriptor(
  name='SpiritDeleteRequest',
  full_name='gogrpc.SpiritDeleteRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='spirit', full_name='gogrpc.SpiritDeleteRequest.spirit', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=497,
  serialized_end=550,
)


_SPIRITSEARCHREQUEST = _descriptor.Descriptor(
  name='SpiritSearchRequest',
  full_name='gogrpc.SpiritSearchRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='spirit', full_name='gogrpc.SpiritSearchRequest.spirit', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=552,
  serialized_end=605,
)


_SPIRITCREATIONRESPONSE = _descriptor.Descriptor(
  name='SpiritCreationResponse',
  full_name='gogrpc.SpiritCreationResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='spirit', full_name='gogrpc.SpiritCreationResponse.spirit', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=607,
  serialized_end=663,
)


_SPIRITUPDATERESPONSE = _descriptor.Descriptor(
  name='SpiritUpdateResponse',
  full_name='gogrpc.SpiritUpdateResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='spirit', full_name='gogrpc.SpiritUpdateResponse.spirit', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=665,
  serialized_end=719,
)


_SPIRITDELETERESPONSE = _descriptor.Descriptor(
  name='SpiritDeleteResponse',
  full_name='gogrpc.SpiritDeleteResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='deleted', full_name='gogrpc.SpiritDeleteResponse.deleted', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=721,
  serialized_end=760,
)


_SPIRITSEARCHRESPONSE = _descriptor.Descriptor(
  name='SpiritSearchResponse',
  full_name='gogrpc.SpiritSearchResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='spirit', full_name='gogrpc.SpiritSearchResponse.spirit', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=762,
  serialized_end=816,
)

_SPIRIT.fields_by_name['type'].enum_type = _SPIRIT_SPIRITTYPE
_SPIRIT_SPIRITTYPE.containing_type = _SPIRIT
_SPIRITCREATIONREQUEST.fields_by_name['spirit'].message_type = _SPIRIT
_SPIRITUPDATEREQUEST.fields_by_name['spirit'].message_type = _SPIRIT
_SPIRITDELETEREQUEST.fields_by_name['spirit'].message_type = _SPIRIT
_SPIRITSEARCHREQUEST.fields_by_name['spirit'].message_type = _SPIRIT
_SPIRITCREATIONRESPONSE.fields_by_name['spirit'].message_type = _SPIRIT
_SPIRITUPDATERESPONSE.fields_by_name['spirit'].message_type = _SPIRIT
_SPIRITSEARCHRESPONSE.fields_by_name['spirit'].message_type = _SPIRIT
DESCRIPTOR.message_types_by_name['Spirit'] = _SPIRIT
DESCRIPTOR.message_types_by_name['SpiritCreationRequest'] = _SPIRITCREATIONREQUEST
DESCRIPTOR.message_types_by_name['SpiritUpdateRequest'] = _SPIRITUPDATEREQUEST
DESCRIPTOR.message_types_by_name['SpiritDeleteRequest'] = _SPIRITDELETEREQUEST
DESCRIPTOR.message_types_by_name['SpiritSearchRequest'] = _SPIRITSEARCHREQUEST
DESCRIPTOR.message_types_by_name['SpiritCreationResponse'] = _SPIRITCREATIONRESPONSE
DESCRIPTOR.message_types_by_name['SpiritUpdateResponse'] = _SPIRITUPDATERESPONSE
DESCRIPTOR.message_types_by_name['SpiritDeleteResponse'] = _SPIRITDELETERESPONSE
DESCRIPTOR.message_types_by_name['SpiritSearchResponse'] = _SPIRITSEARCHRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Spirit = _reflection.GeneratedProtocolMessageType('Spirit', (_message.Message,), {
  'DESCRIPTOR' : _SPIRIT,
  '__module__' : 'spirits_pb2'
  # @@protoc_insertion_point(class_scope:gogrpc.Spirit)
  })
_sym_db.RegisterMessage(Spirit)

SpiritCreationRequest = _reflection.GeneratedProtocolMessageType('SpiritCreationRequest', (_message.Message,), {
  'DESCRIPTOR' : _SPIRITCREATIONREQUEST,
  '__module__' : 'spirits_pb2'
  # @@protoc_insertion_point(class_scope:gogrpc.SpiritCreationRequest)
  })
_sym_db.RegisterMessage(SpiritCreationRequest)

SpiritUpdateRequest = _reflection.GeneratedProtocolMessageType('SpiritUpdateRequest', (_message.Message,), {
  'DESCRIPTOR' : _SPIRITUPDATEREQUEST,
  '__module__' : 'spirits_pb2'
  # @@protoc_insertion_point(class_scope:gogrpc.SpiritUpdateRequest)
  })
_sym_db.RegisterMessage(SpiritUpdateRequest)

SpiritDeleteRequest = _reflection.GeneratedProtocolMessageType('SpiritDeleteRequest', (_message.Message,), {
  'DESCRIPTOR' : _SPIRITDELETEREQUEST,
  '__module__' : 'spirits_pb2'
  # @@protoc_insertion_point(class_scope:gogrpc.SpiritDeleteRequest)
  })
_sym_db.RegisterMessage(SpiritDeleteRequest)

SpiritSearchRequest = _reflection.GeneratedProtocolMessageType('SpiritSearchRequest', (_message.Message,), {
  'DESCRIPTOR' : _SPIRITSEARCHREQUEST,
  '__module__' : 'spirits_pb2'
  # @@protoc_insertion_point(class_scope:gogrpc.SpiritSearchRequest)
  })
_sym_db.RegisterMessage(SpiritSearchRequest)

SpiritCreationResponse = _reflection.GeneratedProtocolMessageType('SpiritCreationResponse', (_message.Message,), {
  'DESCRIPTOR' : _SPIRITCREATIONRESPONSE,
  '__module__' : 'spirits_pb2'
  # @@protoc_insertion_point(class_scope:gogrpc.SpiritCreationResponse)
  })
_sym_db.RegisterMessage(SpiritCreationResponse)

SpiritUpdateResponse = _reflection.GeneratedProtocolMessageType('SpiritUpdateResponse', (_message.Message,), {
  'DESCRIPTOR' : _SPIRITUPDATERESPONSE,
  '__module__' : 'spirits_pb2'
  # @@protoc_insertion_point(class_scope:gogrpc.SpiritUpdateResponse)
  })
_sym_db.RegisterMessage(SpiritUpdateResponse)

SpiritDeleteResponse = _reflection.GeneratedProtocolMessageType('SpiritDeleteResponse', (_message.Message,), {
  'DESCRIPTOR' : _SPIRITDELETERESPONSE,
  '__module__' : 'spirits_pb2'
  # @@protoc_insertion_point(class_scope:gogrpc.SpiritDeleteResponse)
  })
_sym_db.RegisterMessage(SpiritDeleteResponse)

SpiritSearchResponse = _reflection.GeneratedProtocolMessageType('SpiritSearchResponse', (_message.Message,), {
  'DESCRIPTOR' : _SPIRITSEARCHRESPONSE,
  '__module__' : 'spirits_pb2'
  # @@protoc_insertion_point(class_scope:gogrpc.SpiritSearchResponse)
  })
_sym_db.RegisterMessage(SpiritSearchResponse)


DESCRIPTOR._options = None

_SPIRITSERVICE = _descriptor.ServiceDescriptor(
  name='SpiritService',
  full_name='gogrpc.SpiritService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=819,
  serialized_end=1148,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateSpirit',
    full_name='gogrpc.SpiritService.CreateSpirit',
    index=0,
    containing_service=None,
    input_type=_SPIRITCREATIONREQUEST,
    output_type=_SPIRITCREATIONRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateSpirit',
    full_name='gogrpc.SpiritService.UpdateSpirit',
    index=1,
    containing_service=None,
    input_type=_SPIRITUPDATEREQUEST,
    output_type=_SPIRITUPDATERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='DeleteSpirit',
    full_name='gogrpc.SpiritService.DeleteSpirit',
    index=2,
    containing_service=None,
    input_type=_SPIRITDELETEREQUEST,
    output_type=_SPIRITDELETERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SearchSpirit',
    full_name='gogrpc.SpiritService.SearchSpirit',
    index=3,
    containing_service=None,
    input_type=_SPIRITSEARCHREQUEST,
    output_type=_SPIRITSEARCHRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SPIRITSERVICE)

DESCRIPTOR.services_by_name['SpiritService'] = _SPIRITSERVICE

# @@protoc_insertion_point(module_scope)
