# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: storage_messages.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='storage_messages.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\n\020edu.usfca.cs.dfs',
  serialized_pb=b'\n\x16storage_messages.proto\"=\n\nStoreChunk\x12\x10\n\x08\x66ileName\x18\x01 \x01(\t\x12\x0f\n\x07\x63hunkId\x18\x02 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\" \n\x0cRetrieveFile\x12\x10\n\x08\x66ileName\x18\x04 \x01(\t\"n\n\x15StorageMessageWrapper\x12$\n\rstoreChunkMsg\x18\x05 \x01(\x0b\x32\x0b.StoreChunkH\x00\x12(\n\x0fretrieveFileMsg\x18\x06 \x01(\x0b\x32\r.RetrieveFileH\x00\x42\x05\n\x03msgB\x12\n\x10\x65\x64u.usfca.cs.dfsb\x06proto3'
)




_STORECHUNK = _descriptor.Descriptor(
  name='StoreChunk',
  full_name='StoreChunk',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fileName', full_name='StoreChunk.fileName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='chunkId', full_name='StoreChunk.chunkId', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='StoreChunk.data', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=87,
)


_RETRIEVEFILE = _descriptor.Descriptor(
  name='RetrieveFile',
  full_name='RetrieveFile',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fileName', full_name='RetrieveFile.fileName', index=0,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=121,
)


_STORAGEMESSAGEWRAPPER = _descriptor.Descriptor(
  name='StorageMessageWrapper',
  full_name='StorageMessageWrapper',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='storeChunkMsg', full_name='StorageMessageWrapper.storeChunkMsg', index=0,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='retrieveFileMsg', full_name='StorageMessageWrapper.retrieveFileMsg', index=1,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='msg', full_name='StorageMessageWrapper.msg',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=123,
  serialized_end=233,
)

_STORAGEMESSAGEWRAPPER.fields_by_name['storeChunkMsg'].message_type = _STORECHUNK
_STORAGEMESSAGEWRAPPER.fields_by_name['retrieveFileMsg'].message_type = _RETRIEVEFILE
_STORAGEMESSAGEWRAPPER.oneofs_by_name['msg'].fields.append(
  _STORAGEMESSAGEWRAPPER.fields_by_name['storeChunkMsg'])
_STORAGEMESSAGEWRAPPER.fields_by_name['storeChunkMsg'].containing_oneof = _STORAGEMESSAGEWRAPPER.oneofs_by_name['msg']
_STORAGEMESSAGEWRAPPER.oneofs_by_name['msg'].fields.append(
  _STORAGEMESSAGEWRAPPER.fields_by_name['retrieveFileMsg'])
_STORAGEMESSAGEWRAPPER.fields_by_name['retrieveFileMsg'].containing_oneof = _STORAGEMESSAGEWRAPPER.oneofs_by_name['msg']
DESCRIPTOR.message_types_by_name['StoreChunk'] = _STORECHUNK
DESCRIPTOR.message_types_by_name['RetrieveFile'] = _RETRIEVEFILE
DESCRIPTOR.message_types_by_name['StorageMessageWrapper'] = _STORAGEMESSAGEWRAPPER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StoreChunk = _reflection.GeneratedProtocolMessageType('StoreChunk', (_message.Message,), {
  'DESCRIPTOR' : _STORECHUNK,
  '__module__' : 'storage_messages_pb2'
  # @@protoc_insertion_point(class_scope:StoreChunk)
  })
_sym_db.RegisterMessage(StoreChunk)

RetrieveFile = _reflection.GeneratedProtocolMessageType('RetrieveFile', (_message.Message,), {
  'DESCRIPTOR' : _RETRIEVEFILE,
  '__module__' : 'storage_messages_pb2'
  # @@protoc_insertion_point(class_scope:RetrieveFile)
  })
_sym_db.RegisterMessage(RetrieveFile)

StorageMessageWrapper = _reflection.GeneratedProtocolMessageType('StorageMessageWrapper', (_message.Message,), {
  'DESCRIPTOR' : _STORAGEMESSAGEWRAPPER,
  '__module__' : 'storage_messages_pb2'
  # @@protoc_insertion_point(class_scope:StorageMessageWrapper)
  })
_sym_db.RegisterMessage(StorageMessageWrapper)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
