# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: student.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='student.proto',
  package='com.lc.test',
  syntax='proto2',
  serialized_options=b'\n\013com.lc.testB\010DataInfoH\001',
  serialized_pb=b'\n\rstudent.proto\x12\x0b\x63om.lc.test\"\xed\x01\n\tMyMessage\x12\x32\n\tdata_type\x18\x01 \x02(\x0e\x32\x1f.com.lc.test.MyMessage.DataType\x12\'\n\x07student\x18\x02 \x01(\x0b\x32\x14.com.lc.test.StudentH\x00\x12\x1f\n\x03\x64og\x18\x03 \x01(\x0b\x32\x10.com.lc.test.DogH\x00\x12\x1f\n\x03\x63\x61t\x18\x04 \x01(\x0b\x32\x10.com.lc.test.CatH\x00\"5\n\x08\x44\x61taType\x12\x0f\n\x0bStudentType\x10\x01\x12\x0b\n\x07\x44ogType\x10\x02\x12\x0b\n\x07\x43\x61tType\x10\x03\x42\n\n\x08\x64\x61taBody\"5\n\x07Student\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03\x61ge\x18\x02 \x01(\x05\x12\x0f\n\x07\x61\x64\x64ress\x18\x03 \x01(\t\" \n\x03\x44og\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03\x61ge\x18\x02 \x01(\x05\"!\n\x03\x43\x61t\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04\x63ity\x18\x02 \x01(\tB\x19\n\x0b\x63om.lc.testB\x08\x44\x61taInfoH\x01'
)



_MYMESSAGE_DATATYPE = _descriptor.EnumDescriptor(
  name='DataType',
  full_name='com.lc.test.MyMessage.DataType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='StudentType', index=0, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DogType', index=1, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CatType', index=2, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=203,
  serialized_end=256,
)
_sym_db.RegisterEnumDescriptor(_MYMESSAGE_DATATYPE)


_MYMESSAGE = _descriptor.Descriptor(
  name='MyMessage',
  full_name='com.lc.test.MyMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data_type', full_name='com.lc.test.MyMessage.data_type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='student', full_name='com.lc.test.MyMessage.student', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dog', full_name='com.lc.test.MyMessage.dog', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cat', full_name='com.lc.test.MyMessage.cat', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _MYMESSAGE_DATATYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='dataBody', full_name='com.lc.test.MyMessage.dataBody',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=31,
  serialized_end=268,
)


_STUDENT = _descriptor.Descriptor(
  name='Student',
  full_name='com.lc.test.Student',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='com.lc.test.Student.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='age', full_name='com.lc.test.Student.age', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='address', full_name='com.lc.test.Student.address', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=270,
  serialized_end=323,
)


_DOG = _descriptor.Descriptor(
  name='Dog',
  full_name='com.lc.test.Dog',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='com.lc.test.Dog.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='age', full_name='com.lc.test.Dog.age', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=325,
  serialized_end=357,
)


_CAT = _descriptor.Descriptor(
  name='Cat',
  full_name='com.lc.test.Cat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='com.lc.test.Cat.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='city', full_name='com.lc.test.Cat.city', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=359,
  serialized_end=392,
)

_MYMESSAGE.fields_by_name['data_type'].enum_type = _MYMESSAGE_DATATYPE
_MYMESSAGE.fields_by_name['student'].message_type = _STUDENT
_MYMESSAGE.fields_by_name['dog'].message_type = _DOG
_MYMESSAGE.fields_by_name['cat'].message_type = _CAT
_MYMESSAGE_DATATYPE.containing_type = _MYMESSAGE
_MYMESSAGE.oneofs_by_name['dataBody'].fields.append(
  _MYMESSAGE.fields_by_name['student'])
_MYMESSAGE.fields_by_name['student'].containing_oneof = _MYMESSAGE.oneofs_by_name['dataBody']
_MYMESSAGE.oneofs_by_name['dataBody'].fields.append(
  _MYMESSAGE.fields_by_name['dog'])
_MYMESSAGE.fields_by_name['dog'].containing_oneof = _MYMESSAGE.oneofs_by_name['dataBody']
_MYMESSAGE.oneofs_by_name['dataBody'].fields.append(
  _MYMESSAGE.fields_by_name['cat'])
_MYMESSAGE.fields_by_name['cat'].containing_oneof = _MYMESSAGE.oneofs_by_name['dataBody']
DESCRIPTOR.message_types_by_name['MyMessage'] = _MYMESSAGE
DESCRIPTOR.message_types_by_name['Student'] = _STUDENT
DESCRIPTOR.message_types_by_name['Dog'] = _DOG
DESCRIPTOR.message_types_by_name['Cat'] = _CAT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MyMessage = _reflection.GeneratedProtocolMessageType('MyMessage', (_message.Message,), {
  'DESCRIPTOR' : _MYMESSAGE,
  '__module__' : 'student_pb2'
  # @@protoc_insertion_point(class_scope:com.lc.test.MyMessage)
  })
_sym_db.RegisterMessage(MyMessage)

Student = _reflection.GeneratedProtocolMessageType('Student', (_message.Message,), {
  'DESCRIPTOR' : _STUDENT,
  '__module__' : 'student_pb2'
  # @@protoc_insertion_point(class_scope:com.lc.test.Student)
  })
_sym_db.RegisterMessage(Student)

Dog = _reflection.GeneratedProtocolMessageType('Dog', (_message.Message,), {
  'DESCRIPTOR' : _DOG,
  '__module__' : 'student_pb2'
  # @@protoc_insertion_point(class_scope:com.lc.test.Dog)
  })
_sym_db.RegisterMessage(Dog)

Cat = _reflection.GeneratedProtocolMessageType('Cat', (_message.Message,), {
  'DESCRIPTOR' : _CAT,
  '__module__' : 'student_pb2'
  # @@protoc_insertion_point(class_scope:com.lc.test.Cat)
  })
_sym_db.RegisterMessage(Cat)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
