# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tallMessage.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tallMessage.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n\x11tallMessage.proto\"\xb7\x03\n\x0fTestTallMessage\x12\r\n\x05\x63ount\x18\x01 \x02(\x05\x12\r\n\x05\x64\x61ta0\x18\x02 \x02(\t\x12\r\n\x05\x64\x61ta1\x18\x03 \x02(\t\x12\r\n\x05\x64\x61ta2\x18\x04 \x02(\t\x12\r\n\x05\x64\x61ta3\x18\x05 \x02(\t\x12\r\n\x05\x64\x61ta4\x18\x06 \x02(\t\x12\r\n\x05\x64\x61ta5\x18\x07 \x02(\t\x12\r\n\x05\x64\x61ta6\x18\x08 \x02(\t\x12\r\n\x05\x64\x61ta7\x18\t \x02(\t\x12\r\n\x05\x64\x61ta8\x18\n \x02(\t\x12\r\n\x05\x64\x61ta9\x18\x0b \x02(\t\x12\x0e\n\x06\x64\x61ta10\x18\x0c \x02(\t\x12\x0e\n\x06\x64\x61ta11\x18\r \x02(\t\x12\x0e\n\x06\x64\x61ta12\x18\x0e \x02(\t\x12\x0e\n\x06\x64\x61ta13\x18\x0f \x02(\t\x12\x0e\n\x06\x64\x61ta14\x18\x10 \x02(\t\x12\x0e\n\x06\x64\x61ta15\x18\x11 \x02(\t\x12\x0e\n\x06\x64\x61ta16\x18\x12 \x02(\t\x12\x0e\n\x06\x64\x61ta17\x18\x13 \x02(\t\x12\x0e\n\x06\x64\x61ta18\x18\x14 \x02(\t\x12\x0e\n\x06\x64\x61ta19\x18\x15 \x02(\t\x12\x0e\n\x06\x64\x61ta20\x18\x16 \x02(\t\x12\x0e\n\x06\x64\x61ta21\x18\x17 \x02(\t\x12\x0e\n\x06\x64\x61ta22\x18\x18 \x02(\t\x12\x0e\n\x06\x64\x61ta23\x18\x19 \x02(\t\x12\x0e\n\x06\x64\x61ta24\x18\x1a \x02(\t\x12\x0f\n\x07isFinal\x18\x1b \x02(\x08'
)




_TESTTALLMESSAGE = _descriptor.Descriptor(
  name='TestTallMessage',
  full_name='TestTallMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='count', full_name='TestTallMessage.count', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data0', full_name='TestTallMessage.data0', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data1', full_name='TestTallMessage.data1', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data2', full_name='TestTallMessage.data2', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data3', full_name='TestTallMessage.data3', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data4', full_name='TestTallMessage.data4', index=5,
      number=6, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data5', full_name='TestTallMessage.data5', index=6,
      number=7, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data6', full_name='TestTallMessage.data6', index=7,
      number=8, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data7', full_name='TestTallMessage.data7', index=8,
      number=9, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data8', full_name='TestTallMessage.data8', index=9,
      number=10, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data9', full_name='TestTallMessage.data9', index=10,
      number=11, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data10', full_name='TestTallMessage.data10', index=11,
      number=12, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data11', full_name='TestTallMessage.data11', index=12,
      number=13, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data12', full_name='TestTallMessage.data12', index=13,
      number=14, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data13', full_name='TestTallMessage.data13', index=14,
      number=15, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data14', full_name='TestTallMessage.data14', index=15,
      number=16, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data15', full_name='TestTallMessage.data15', index=16,
      number=17, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data16', full_name='TestTallMessage.data16', index=17,
      number=18, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data17', full_name='TestTallMessage.data17', index=18,
      number=19, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data18', full_name='TestTallMessage.data18', index=19,
      number=20, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data19', full_name='TestTallMessage.data19', index=20,
      number=21, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data20', full_name='TestTallMessage.data20', index=21,
      number=22, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data21', full_name='TestTallMessage.data21', index=22,
      number=23, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data22', full_name='TestTallMessage.data22', index=23,
      number=24, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data23', full_name='TestTallMessage.data23', index=24,
      number=25, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data24', full_name='TestTallMessage.data24', index=25,
      number=26, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='isFinal', full_name='TestTallMessage.isFinal', index=26,
      number=27, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=461,
)

DESCRIPTOR.message_types_by_name['TestTallMessage'] = _TESTTALLMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TestTallMessage = _reflection.GeneratedProtocolMessageType('TestTallMessage', (_message.Message,), {
  'DESCRIPTOR' : _TESTTALLMESSAGE,
  '__module__' : 'tallMessage_pb2'
  # @@protoc_insertion_point(class_scope:TestTallMessage)
  })
_sym_db.RegisterMessage(TestTallMessage)


# @@protoc_insertion_point(module_scope)
