# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test6.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='test6.proto',
  package='proto',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n\x0btest6.proto\x12\x05proto\"8\n\x08UserInfo\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0e\n\x06length\x18\x02 \x01(\x05\x12\x0b\n\x03\x63nt\x18\x03 \x01(\x05*\x0c\n\x03\x46OO\x12\x05\n\x01x\x10\x00'
)

_FOO = _descriptor.EnumDescriptor(
  name='FOO',
  full_name='proto.FOO',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='x', index=0, number=0,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=80,
  serialized_end=92,
)
_sym_db.RegisterEnumDescriptor(_FOO)

FOO = enum_type_wrapper.EnumTypeWrapper(_FOO)
x = 0



_USERINFO = _descriptor.Descriptor(
  name='UserInfo',
  full_name='proto.UserInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='proto.UserInfo.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='length', full_name='proto.UserInfo.length', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cnt', full_name='proto.UserInfo.cnt', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=78,
)

DESCRIPTOR.message_types_by_name['UserInfo'] = _USERINFO
DESCRIPTOR.enum_types_by_name['FOO'] = _FOO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UserInfo = _reflection.GeneratedProtocolMessageType('UserInfo', (_message.Message,), {
  'DESCRIPTOR' : _USERINFO,
  '__module__' : 'test6_pb2'
  # @@protoc_insertion_point(class_scope:proto.UserInfo)
  })
_sym_db.RegisterMessage(UserInfo)


# @@protoc_insertion_point(module_scope)
