# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TimeSchema.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='TimeSchema.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n\x10TimeSchema.proto\"\'\n\tTimeStamp\x12\x0c\n\x04Time\x18\x01 \x02(\t\x12\x0c\n\x04Tick\x18\x02 \x02(\x04\"(\n\x08HeartMsg\x12\x0c\n\x04Tick\x18\x01 \x02(\r\x12\x0e\n\x03UID\x18\x02 \x01(\x04:\x01\x30\"@\n\x08\x42roadMsg\x12\r\n\x05Title\x18\x01 \x02(\t\x12\x0f\n\x07Message\x18\x02 \x02(\t\x12\x14\n\tTimeStamp\x18\x03 \x01(\x04:\x01\x30\"z\n\x07PkgHead\x12#\n\x03\x43md\x18\x01 \x02(\x0e\x32\x0b.CmdActions:\tCMD_HEART\x12\x0f\n\x07\x43mdType\x18\x02 \x02(\r\x12\x0e\n\x06\x43mdSeq\x18\x03 \x02(\r\x12\r\n\x05SrcID\x18\x04 \x02(\r\x12\r\n\x05\x44stID\x18\x05 \x02(\r\x12\x0b\n\x03UID\x18\x06 \x02(\x04\"d\n\x07PkgBody\x12\x1a\n\x04Time\x18\x01 \x01(\x0b\x32\n.TimeStampH\x00\x12\x1a\n\x05Heart\x18\x02 \x01(\x0b\x32\t.HeartMsgH\x00\x12\x19\n\x04Info\x18\x03 \x01(\x0b\x32\t.BroadMsgH\x00\x42\x06\n\x04\x42ody\";\n\tCltSvrPkg\x12\x16\n\x04Head\x18\x01 \x02(\x0b\x32\x08.PkgHead\x12\x16\n\x04\x44\x61ta\x18\x02 \x02(\x0b\x32\x08.PkgBody*I\n\nCmdActions\x12\x0f\n\x0b\x43MD_UNKNOWN\x10\x00\x12\x0c\n\x08\x43MD_TIME\x10\x01\x12\r\n\tCMD_HEART\x10\x02\x12\r\n\tCMD_BROAD\x10\x03'
)

_CMDACTIONS = _descriptor.EnumDescriptor(
  name='CmdActions',
  full_name='CmdActions',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CMD_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CMD_TIME', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CMD_HEART', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CMD_BROAD', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=456,
  serialized_end=529,
)
_sym_db.RegisterEnumDescriptor(_CMDACTIONS)

CmdActions = enum_type_wrapper.EnumTypeWrapper(_CMDACTIONS)
CMD_UNKNOWN = 0
CMD_TIME = 1
CMD_HEART = 2
CMD_BROAD = 3



_TIMESTAMP = _descriptor.Descriptor(
  name='TimeStamp',
  full_name='TimeStamp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Time', full_name='TimeStamp.Time', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Tick', full_name='TimeStamp.Tick', index=1,
      number=2, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=59,
)


_HEARTMSG = _descriptor.Descriptor(
  name='HeartMsg',
  full_name='HeartMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Tick', full_name='HeartMsg.Tick', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='UID', full_name='HeartMsg.UID', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=101,
)


_BROADMSG = _descriptor.Descriptor(
  name='BroadMsg',
  full_name='BroadMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Title', full_name='BroadMsg.Title', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Message', full_name='BroadMsg.Message', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='TimeStamp', full_name='BroadMsg.TimeStamp', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=167,
)


_PKGHEAD = _descriptor.Descriptor(
  name='PkgHead',
  full_name='PkgHead',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Cmd', full_name='PkgHead.Cmd', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=True, default_value=2,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='CmdType', full_name='PkgHead.CmdType', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='CmdSeq', full_name='PkgHead.CmdSeq', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='SrcID', full_name='PkgHead.SrcID', index=3,
      number=4, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='DstID', full_name='PkgHead.DstID', index=4,
      number=5, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='UID', full_name='PkgHead.UID', index=5,
      number=6, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=169,
  serialized_end=291,
)


_PKGBODY = _descriptor.Descriptor(
  name='PkgBody',
  full_name='PkgBody',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Time', full_name='PkgBody.Time', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Heart', full_name='PkgBody.Heart', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Info', full_name='PkgBody.Info', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='Body', full_name='PkgBody.Body',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=293,
  serialized_end=393,
)


_CLTSVRPKG = _descriptor.Descriptor(
  name='CltSvrPkg',
  full_name='CltSvrPkg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Head', full_name='CltSvrPkg.Head', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Data', full_name='CltSvrPkg.Data', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=395,
  serialized_end=454,
)

_PKGHEAD.fields_by_name['Cmd'].enum_type = _CMDACTIONS
_PKGBODY.fields_by_name['Time'].message_type = _TIMESTAMP
_PKGBODY.fields_by_name['Heart'].message_type = _HEARTMSG
_PKGBODY.fields_by_name['Info'].message_type = _BROADMSG
_PKGBODY.oneofs_by_name['Body'].fields.append(
  _PKGBODY.fields_by_name['Time'])
_PKGBODY.fields_by_name['Time'].containing_oneof = _PKGBODY.oneofs_by_name['Body']
_PKGBODY.oneofs_by_name['Body'].fields.append(
  _PKGBODY.fields_by_name['Heart'])
_PKGBODY.fields_by_name['Heart'].containing_oneof = _PKGBODY.oneofs_by_name['Body']
_PKGBODY.oneofs_by_name['Body'].fields.append(
  _PKGBODY.fields_by_name['Info'])
_PKGBODY.fields_by_name['Info'].containing_oneof = _PKGBODY.oneofs_by_name['Body']
_CLTSVRPKG.fields_by_name['Head'].message_type = _PKGHEAD
_CLTSVRPKG.fields_by_name['Data'].message_type = _PKGBODY
DESCRIPTOR.message_types_by_name['TimeStamp'] = _TIMESTAMP
DESCRIPTOR.message_types_by_name['HeartMsg'] = _HEARTMSG
DESCRIPTOR.message_types_by_name['BroadMsg'] = _BROADMSG
DESCRIPTOR.message_types_by_name['PkgHead'] = _PKGHEAD
DESCRIPTOR.message_types_by_name['PkgBody'] = _PKGBODY
DESCRIPTOR.message_types_by_name['CltSvrPkg'] = _CLTSVRPKG
DESCRIPTOR.enum_types_by_name['CmdActions'] = _CMDACTIONS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TimeStamp = _reflection.GeneratedProtocolMessageType('TimeStamp', (_message.Message,), {
  'DESCRIPTOR' : _TIMESTAMP,
  '__module__' : 'TimeSchema_pb2'
  # @@protoc_insertion_point(class_scope:TimeStamp)
  })
_sym_db.RegisterMessage(TimeStamp)

HeartMsg = _reflection.GeneratedProtocolMessageType('HeartMsg', (_message.Message,), {
  'DESCRIPTOR' : _HEARTMSG,
  '__module__' : 'TimeSchema_pb2'
  # @@protoc_insertion_point(class_scope:HeartMsg)
  })
_sym_db.RegisterMessage(HeartMsg)

BroadMsg = _reflection.GeneratedProtocolMessageType('BroadMsg', (_message.Message,), {
  'DESCRIPTOR' : _BROADMSG,
  '__module__' : 'TimeSchema_pb2'
  # @@protoc_insertion_point(class_scope:BroadMsg)
  })
_sym_db.RegisterMessage(BroadMsg)

PkgHead = _reflection.GeneratedProtocolMessageType('PkgHead', (_message.Message,), {
  'DESCRIPTOR' : _PKGHEAD,
  '__module__' : 'TimeSchema_pb2'
  # @@protoc_insertion_point(class_scope:PkgHead)
  })
_sym_db.RegisterMessage(PkgHead)

PkgBody = _reflection.GeneratedProtocolMessageType('PkgBody', (_message.Message,), {
  'DESCRIPTOR' : _PKGBODY,
  '__module__' : 'TimeSchema_pb2'
  # @@protoc_insertion_point(class_scope:PkgBody)
  })
_sym_db.RegisterMessage(PkgBody)

CltSvrPkg = _reflection.GeneratedProtocolMessageType('CltSvrPkg', (_message.Message,), {
  'DESCRIPTOR' : _CLTSVRPKG,
  '__module__' : 'TimeSchema_pb2'
  # @@protoc_insertion_point(class_scope:CltSvrPkg)
  })
_sym_db.RegisterMessage(CltSvrPkg)


# @@protoc_insertion_point(module_scope)
