# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transaction.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='transaction.proto',
  package='com.thoughtworks.zpay',
  syntax='proto3',
  serialized_options=b'\n\025com.thoughtworks.zpay',
  serialized_pb=b'\n\x11transaction.proto\x12\x15\x63om.thoughtworks.zpay\"\xa1\x02\n\x14\x43ompletedTransaction\x12\x1d\n\x15transaction_reference\x18\x01 \x01(\t\x12,\n\x06\x61mount\x18\x02 \x01(\x0b\x32\x1c.com.thoughtworks.zpay.Money\x12\x35\n\rdebit_account\x18\x03 \x01(\x0b\x32\x1e.com.thoughtworks.zpay.Account\x12\x36\n\x0e\x63redit_account\x18\x04 \x01(\x0b\x32\x1e.com.thoughtworks.zpay.Account\x12\x13\n\x0b\x64\x65scription\x18\x05 \x01(\t\x12\x38\n\x06status\x18\x06 \x01(\x0e\x32(.com.thoughtworks.zpay.TransactionStatus\"N\n\x05Money\x12\x36\n\rcurrency_code\x18\x01 \x01(\x0e\x32\x1f.com.thoughtworks.zpay.Currency\x12\r\n\x05value\x18\x02 \x01(\x12\"^\n\x07\x41\x63\x63ount\x12\x37\n\x0b\x61\x63\x63ountType\x18\x01 \x01(\x0e\x32\".com.thoughtworks.zpay.AccountType\x12\x1a\n\x12\x61\x63\x63ount_identifier\x18\x02 \x01(\t*l\n\x0b\x41\x63\x63ountType\x12\x18\n\x14\x41\x43\x43OUNT_TYPE_UNKNOWN\x10\x00\x12\x10\n\x0cPAYTM_WALLET\x10\x01\x12\n\n\x06UPI_ID\x10\x02\x12\x0f\n\x0b\x43REDIT_CARD\x10\x03\x12\x14\n\x10INTERNAL_ACCOUNT\x10\x04*D\n\x08\x43urrency\x12\x14\n\x10\x43URRENCY_UNKNOWN\x10\x00\x12\x10\n\x0c\x43URRENCY_USD\x10\x01\x12\x10\n\x0c\x43URRENCY_INR\x10\x02*b\n\x11TransactionStatus\x12\x12\n\x0eSTATUS_UNKNOWN\x10\x00\x12\r\n\tINITIATED\x10\x01\x12\x10\n\x0c\x42\x41NK_FAILURE\x10\x02\x12\x0b\n\x07SUCCESS\x10\x03\x12\x0b\n\x07SUSPECT\x10\x04\x42\x17\n\x15\x63om.thoughtworks.zpayb\x06proto3'
)

_ACCOUNTTYPE = _descriptor.EnumDescriptor(
  name='AccountType',
  full_name='com.thoughtworks.zpay.AccountType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ACCOUNT_TYPE_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PAYTM_WALLET', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UPI_ID', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CREDIT_CARD', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INTERNAL_ACCOUNT', index=4, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=512,
  serialized_end=620,
)
_sym_db.RegisterEnumDescriptor(_ACCOUNTTYPE)

AccountType = enum_type_wrapper.EnumTypeWrapper(_ACCOUNTTYPE)
_CURRENCY = _descriptor.EnumDescriptor(
  name='Currency',
  full_name='com.thoughtworks.zpay.Currency',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CURRENCY_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CURRENCY_USD', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CURRENCY_INR', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=622,
  serialized_end=690,
)
_sym_db.RegisterEnumDescriptor(_CURRENCY)

Currency = enum_type_wrapper.EnumTypeWrapper(_CURRENCY)
_TRANSACTIONSTATUS = _descriptor.EnumDescriptor(
  name='TransactionStatus',
  full_name='com.thoughtworks.zpay.TransactionStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='STATUS_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INITIATED', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BANK_FAILURE', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SUSPECT', index=4, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=692,
  serialized_end=790,
)
_sym_db.RegisterEnumDescriptor(_TRANSACTIONSTATUS)

TransactionStatus = enum_type_wrapper.EnumTypeWrapper(_TRANSACTIONSTATUS)
ACCOUNT_TYPE_UNKNOWN = 0
PAYTM_WALLET = 1
UPI_ID = 2
CREDIT_CARD = 3
INTERNAL_ACCOUNT = 4
CURRENCY_UNKNOWN = 0
CURRENCY_USD = 1
CURRENCY_INR = 2
STATUS_UNKNOWN = 0
INITIATED = 1
BANK_FAILURE = 2
SUCCESS = 3
SUSPECT = 4



_COMPLETEDTRANSACTION = _descriptor.Descriptor(
  name='CompletedTransaction',
  full_name='com.thoughtworks.zpay.CompletedTransaction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='transaction_reference', full_name='com.thoughtworks.zpay.CompletedTransaction.transaction_reference', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='amount', full_name='com.thoughtworks.zpay.CompletedTransaction.amount', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='debit_account', full_name='com.thoughtworks.zpay.CompletedTransaction.debit_account', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='credit_account', full_name='com.thoughtworks.zpay.CompletedTransaction.credit_account', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='description', full_name='com.thoughtworks.zpay.CompletedTransaction.description', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='com.thoughtworks.zpay.CompletedTransaction.status', index=5,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=334,
)


_MONEY = _descriptor.Descriptor(
  name='Money',
  full_name='com.thoughtworks.zpay.Money',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='currency_code', full_name='com.thoughtworks.zpay.Money.currency_code', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='com.thoughtworks.zpay.Money.value', index=1,
      number=2, type=18, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=336,
  serialized_end=414,
)


_ACCOUNT = _descriptor.Descriptor(
  name='Account',
  full_name='com.thoughtworks.zpay.Account',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='accountType', full_name='com.thoughtworks.zpay.Account.accountType', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='account_identifier', full_name='com.thoughtworks.zpay.Account.account_identifier', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=416,
  serialized_end=510,
)

_COMPLETEDTRANSACTION.fields_by_name['amount'].message_type = _MONEY
_COMPLETEDTRANSACTION.fields_by_name['debit_account'].message_type = _ACCOUNT
_COMPLETEDTRANSACTION.fields_by_name['credit_account'].message_type = _ACCOUNT
_COMPLETEDTRANSACTION.fields_by_name['status'].enum_type = _TRANSACTIONSTATUS
_MONEY.fields_by_name['currency_code'].enum_type = _CURRENCY
_ACCOUNT.fields_by_name['accountType'].enum_type = _ACCOUNTTYPE
DESCRIPTOR.message_types_by_name['CompletedTransaction'] = _COMPLETEDTRANSACTION
DESCRIPTOR.message_types_by_name['Money'] = _MONEY
DESCRIPTOR.message_types_by_name['Account'] = _ACCOUNT
DESCRIPTOR.enum_types_by_name['AccountType'] = _ACCOUNTTYPE
DESCRIPTOR.enum_types_by_name['Currency'] = _CURRENCY
DESCRIPTOR.enum_types_by_name['TransactionStatus'] = _TRANSACTIONSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CompletedTransaction = _reflection.GeneratedProtocolMessageType('CompletedTransaction', (_message.Message,), {
  'DESCRIPTOR' : _COMPLETEDTRANSACTION,
  '__module__' : 'transaction_pb2'
  # @@protoc_insertion_point(class_scope:com.thoughtworks.zpay.CompletedTransaction)
  })
_sym_db.RegisterMessage(CompletedTransaction)

Money = _reflection.GeneratedProtocolMessageType('Money', (_message.Message,), {
  'DESCRIPTOR' : _MONEY,
  '__module__' : 'transaction_pb2'
  # @@protoc_insertion_point(class_scope:com.thoughtworks.zpay.Money)
  })
_sym_db.RegisterMessage(Money)

Account = _reflection.GeneratedProtocolMessageType('Account', (_message.Message,), {
  'DESCRIPTOR' : _ACCOUNT,
  '__module__' : 'transaction_pb2'
  # @@protoc_insertion_point(class_scope:com.thoughtworks.zpay.Account)
  })
_sym_db.RegisterMessage(Account)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
