# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UserInfo.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='UserInfo.proto',
  package='com.huobi.cy.protobuf',
  syntax='proto3',
  serialized_options=b'B\010UserInfo',
  serialized_pb=b'\n\x0eUserInfo.proto\x12\x15\x63om.huobi.cy.protobuf\")\n\x04User\x12\x0f\n\x07\x61\x63\x63ount\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"9\n\x0bListOfUsers\x12*\n\x05users\x18\x01 \x03(\x0b\x32\x1b.com.huobi.cy.protobuf.UserB\nB\x08UserInfob\x06proto3'
)




_USER = _descriptor.Descriptor(
  name='User',
  full_name='com.huobi.cy.protobuf.User',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='account', full_name='com.huobi.cy.protobuf.User.account', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='password', full_name='com.huobi.cy.protobuf.User.password', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=82,
)


_LISTOFUSERS = _descriptor.Descriptor(
  name='ListOfUsers',
  full_name='com.huobi.cy.protobuf.ListOfUsers',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='users', full_name='com.huobi.cy.protobuf.ListOfUsers.users', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=84,
  serialized_end=141,
)

_LISTOFUSERS.fields_by_name['users'].message_type = _USER
DESCRIPTOR.message_types_by_name['User'] = _USER
DESCRIPTOR.message_types_by_name['ListOfUsers'] = _LISTOFUSERS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

User = _reflection.GeneratedProtocolMessageType('User', (_message.Message,), {
  'DESCRIPTOR' : _USER,
  '__module__' : 'UserInfo_pb2'
  # @@protoc_insertion_point(class_scope:com.huobi.cy.protobuf.User)
  })
_sym_db.RegisterMessage(User)

ListOfUsers = _reflection.GeneratedProtocolMessageType('ListOfUsers', (_message.Message,), {
  'DESCRIPTOR' : _LISTOFUSERS,
  '__module__' : 'UserInfo_pb2'
  # @@protoc_insertion_point(class_scope:com.huobi.cy.protobuf.ListOfUsers)
  })
_sym_db.RegisterMessage(ListOfUsers)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
