# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wind.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='wind.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\n\024com.example.protobufB\007WindGps',
  serialized_pb=b'\n\nwind.proto\"_\n\x04Wind\x12\x16\n\x03gps\x18\x01 \x03(\x0b\x32\t.Wind.Gps\x1a?\n\x03Gps\x12\x11\n\tlongitude\x18\x01 \x01(\x01\x12\x11\n\tdimension\x18\x02 \x01(\x01\x12\x12\n\ncoordinate\x18\x03 \x01(\x01\x42\x1f\n\x14\x63om.example.protobufB\x07WindGpsb\x06proto3'
)




_WIND_GPS = _descriptor.Descriptor(
  name='Gps',
  full_name='Wind.Gps',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='longitude', full_name='Wind.Gps.longitude', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dimension', full_name='Wind.Gps.dimension', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='coordinate', full_name='Wind.Gps.coordinate', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=109,
)

_WIND = _descriptor.Descriptor(
  name='Wind',
  full_name='Wind',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='gps', full_name='Wind.gps', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_WIND_GPS, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=109,
)

_WIND_GPS.containing_type = _WIND
_WIND.fields_by_name['gps'].message_type = _WIND_GPS
DESCRIPTOR.message_types_by_name['Wind'] = _WIND
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Wind = _reflection.GeneratedProtocolMessageType('Wind', (_message.Message,), {

  'Gps' : _reflection.GeneratedProtocolMessageType('Gps', (_message.Message,), {
    'DESCRIPTOR' : _WIND_GPS,
    '__module__' : 'wind_pb2'
    # @@protoc_insertion_point(class_scope:Wind.Gps)
    })
  ,
  'DESCRIPTOR' : _WIND,
  '__module__' : 'wind_pb2'
  # @@protoc_insertion_point(class_scope:Wind)
  })
_sym_db.RegisterMessage(Wind)
_sym_db.RegisterMessage(Wind.Gps)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
