# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yages-schema.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='yages-schema.proto',
  package='yages',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x12yages-schema.proto\x12\x05yages\"\x07\n\x05\x45mpty\"\x17\n\x07\x43ontent\x12\x0c\n\x04text\x18\x01 \x01(\t2[\n\x04\x45\x63ho\x12&\n\x04Ping\x12\x0c.yages.Empty\x1a\x0e.yages.Content\"\x00\x12+\n\x07Reverse\x12\x0e.yages.Content\x1a\x0e.yages.Content\"\x00\x62\x06proto3'
)




_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='yages.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=36,
)


_CONTENT = _descriptor.Descriptor(
  name='Content',
  full_name='yages.Content',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='yages.Content.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=61,
)

DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['Content'] = _CONTENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'yages_schema_pb2'
  # @@protoc_insertion_point(class_scope:yages.Empty)
  })
_sym_db.RegisterMessage(Empty)

Content = _reflection.GeneratedProtocolMessageType('Content', (_message.Message,), {
  'DESCRIPTOR' : _CONTENT,
  '__module__' : 'yages_schema_pb2'
  # @@protoc_insertion_point(class_scope:yages.Content)
  })
_sym_db.RegisterMessage(Content)



_ECHO = _descriptor.ServiceDescriptor(
  name='Echo',
  full_name='yages.Echo',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=63,
  serialized_end=154,
  methods=[
  _descriptor.MethodDescriptor(
    name='Ping',
    full_name='yages.Echo.Ping',
    index=0,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_CONTENT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Reverse',
    full_name='yages.Echo.Reverse',
    index=1,
    containing_service=None,
    input_type=_CONTENT,
    output_type=_CONTENT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ECHO)

DESCRIPTOR.services_by_name['Echo'] = _ECHO

# @@protoc_insertion_point(module_scope)
