# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GpsLocation.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='GpsLocation.proto',
  package='xebia',
  syntax='proto3',
  serialized_options=b'\n\030com.xebia.protobuf.protoB\021GpsLocationProtos',
  serialized_pb=b'\n\x11GpsLocation.proto\x12\x05xebia\"2\n\x0bGpsLocation\x12\x10\n\x08latitude\x18\x01 \x01(\x11\x12\x11\n\tlongitude\x18\x02 \x01(\x11\x42-\n\x18\x63om.xebia.protobuf.protoB\x11GpsLocationProtosb\x06proto3'
)




_GPSLOCATION = _descriptor.Descriptor(
  name='GpsLocation',
  full_name='xebia.GpsLocation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='latitude', full_name='xebia.GpsLocation.latitude', index=0,
      number=1, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='xebia.GpsLocation.longitude', index=1,
      number=2, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=78,
)

DESCRIPTOR.message_types_by_name['GpsLocation'] = _GPSLOCATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GpsLocation = _reflection.GeneratedProtocolMessageType('GpsLocation', (_message.Message,), {
  'DESCRIPTOR' : _GPSLOCATION,
  '__module__' : 'GpsLocation_pb2'
  # @@protoc_insertion_point(class_scope:xebia.GpsLocation)
  })
_sym_db.RegisterMessage(GpsLocation)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
