# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Person.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import SearchResponse_pb2 as SearchResponse__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Person.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0cPerson.proto\x1a\x14SearchResponse.proto\"\x99\x01\n\x0bPhoneNumber\x12\x0e\n\x06number\x18\x01 \x01(\t\x12$\n\x04type\x18\x02 \x01(\x0e\x32\x16.PhoneNumber.PhoneType\x12\'\n\x0esearchResponse\x18\x03 \x01(\x0b\x32\x0f.SearchResponse\"+\n\tPhoneType\x12\n\n\x06MOBILE\x10\x00\x12\x08\n\x04HOME\x10\x01\x12\x08\n\x04WORK\x10\x02\x62\x06proto3'
  ,
  dependencies=[SearchResponse__pb2.DESCRIPTOR,])



_PHONENUMBER_PHONETYPE = _descriptor.EnumDescriptor(
  name='PhoneType',
  full_name='PhoneNumber.PhoneType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MOBILE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HOME', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WORK', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=149,
  serialized_end=192,
)
_sym_db.RegisterEnumDescriptor(_PHONENUMBER_PHONETYPE)


_PHONENUMBER = _descriptor.Descriptor(
  name='PhoneNumber',
  full_name='PhoneNumber',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='number', full_name='PhoneNumber.number', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='PhoneNumber.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='searchResponse', full_name='PhoneNumber.searchResponse', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _PHONENUMBER_PHONETYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=192,
)

_PHONENUMBER.fields_by_name['type'].enum_type = _PHONENUMBER_PHONETYPE
_PHONENUMBER.fields_by_name['searchResponse'].message_type = SearchResponse__pb2._SEARCHRESPONSE
_PHONENUMBER_PHONETYPE.containing_type = _PHONENUMBER
DESCRIPTOR.message_types_by_name['PhoneNumber'] = _PHONENUMBER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PhoneNumber = _reflection.GeneratedProtocolMessageType('PhoneNumber', (_message.Message,), {
  'DESCRIPTOR' : _PHONENUMBER,
  '__module__' : 'Person_pb2'
  # @@protoc_insertion_point(class_scope:PhoneNumber)
  })
_sym_db.RegisterMessage(PhoneNumber)


# @@protoc_insertion_point(module_scope)
