# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Player.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import vector_pb2 as vector__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Player.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n\x0cPlayer.proto\x1a\x0cvector.proto\"5\n\tPlayerPos\x12\x10\n\x08playerID\x18\x01 \x02(\r\x12\x16\n\x03pos\x18\x02 \x02(\x0b\x32\t.vector3D'
  ,
  dependencies=[vector__pb2.DESCRIPTOR,])




_PLAYERPOS = _descriptor.Descriptor(
  name='PlayerPos',
  full_name='PlayerPos',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='playerID', full_name='PlayerPos.playerID', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pos', full_name='PlayerPos.pos', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=83,
)

_PLAYERPOS.fields_by_name['pos'].message_type = vector__pb2._VECTOR3D
DESCRIPTOR.message_types_by_name['PlayerPos'] = _PLAYERPOS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PlayerPos = _reflection.GeneratedProtocolMessageType('PlayerPos', (_message.Message,), {
  'DESCRIPTOR' : _PLAYERPOS,
  '__module__' : 'Player_pb2'
  # @@protoc_insertion_point(class_scope:PlayerPos)
  })
_sym_db.RegisterMessage(PlayerPos)


# @@protoc_insertion_point(module_scope)
