# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SensorData.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='SensorData.proto',
  package='xebia',
  syntax='proto3',
  serialized_options=b'\n\030com.xebia.protobuf.protoB\020SensorDataProtos',
  serialized_pb=b'\n\x10SensorData.proto\x12\x05xebia\"\xb1\x01\n\nSensorData\x12\x30\n\nsensorType\x18\x01 \x01(\x0e\x32\x1c.xebia.SensorData.SensorType\x12\r\n\x05value\x18\x02 \x01(\x11\x12\x17\n\x0f\x61\x64\x64itionalInfos\x18\x03 \x01(\t\"I\n\nSensorType\x12\x0c\n\x08HUMIDITY\x10\x00\x12\x0f\n\x0bTEMPERATURE\x10\x01\x12\x0e\n\nCOMPACTION\x10\x02\x12\x0c\n\x08SALINITY\x10\x03\x42,\n\x18\x63om.xebia.protobuf.protoB\x10SensorDataProtosb\x06proto3'
)



_SENSORDATA_SENSORTYPE = _descriptor.EnumDescriptor(
  name='SensorType',
  full_name='xebia.SensorData.SensorType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='HUMIDITY', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TEMPERATURE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='COMPACTION', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SALINITY', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=132,
  serialized_end=205,
)
_sym_db.RegisterEnumDescriptor(_SENSORDATA_SENSORTYPE)


_SENSORDATA = _descriptor.Descriptor(
  name='SensorData',
  full_name='xebia.SensorData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sensorType', full_name='xebia.SensorData.sensorType', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='xebia.SensorData.value', index=1,
      number=2, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='additionalInfos', full_name='xebia.SensorData.additionalInfos', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SENSORDATA_SENSORTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=205,
)

_SENSORDATA.fields_by_name['sensorType'].enum_type = _SENSORDATA_SENSORTYPE
_SENSORDATA_SENSORTYPE.containing_type = _SENSORDATA
DESCRIPTOR.message_types_by_name['SensorData'] = _SENSORDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SensorData = _reflection.GeneratedProtocolMessageType('SensorData', (_message.Message,), {
  'DESCRIPTOR' : _SENSORDATA,
  '__module__' : 'SensorData_pb2'
  # @@protoc_insertion_point(class_scope:xebia.SensorData)
  })
_sym_db.RegisterMessage(SensorData)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
